---
sidebar: sidebar 
permalink: br-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Per poter utilizzare il servizio BlueXP backup and recovery , è necessario prima rilevare i dati. Durante la fase di individuazione, BlueXP backup and recovery analizza tutti i volumi e i file negli ambienti di lavoro della tua organizzazione. 
---
= Limitazioni note del BlueXP backup and recovery per i carichi di lavoro di Microsoft SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni.



== Supporto del ciclo di vita dei cloni

* La clonazione da un archivio di oggetti non è supportata.
* Le operazioni di clonazione in blocco non sono supportate per i cloni su richiesta.
* La scelta dei gruppi I non è supportata.
* La scelta delle opzioni QOS (throughput massimo) non è supportata.




== Solo modalità di distribuzione standard

La versione BlueXP backup and recovery funziona solo in modalità di distribuzione standard, non in modalità riservata o privata.



== Restrizione del nome del cluster Windows

Il nome del cluster Windows non può contenere il carattere di sottolineatura (_).



== Problemi di migrazione SnapCenter

La migrazione delle risorse da SnapCenter al BlueXP backup and recovery presenta le seguenti limitazioni.

Per i dettagli su come i criteri SnapCenter migrano ai criteri BlueXP backup and recovery , vedere link:reference-policy-differences-snapcenter.html["Criteri in SnapCenter confrontati con quelli nel BlueXP backup and recovery"] .



=== Limitazioni del gruppo di risorse

Se tutte le risorse in un gruppo di risorse sono protette e una di queste risorse è protetta anche all'esterno del gruppo di risorse, la migrazione da SnapCenter viene bloccata.

*Soluzione alternativa*: proteggere la risorsa in un gruppo di risorse o da sola, ma non in entrambi.



=== Risorse con più policy che utilizzano lo stesso livello di pianificazione non supportate

Non è possibile assegnare più policy che utilizzano lo stesso livello di pianificazione (ad esempio, oraria, giornaliera, settimanale, ecc.) a una risorsa. Il BlueXP backup and recovery non importeranno tali risorse da SnapCenter.

*Soluzione alternativa*: associare a una risorsa solo una policy utilizzando lo stesso livello di pianificazione.



=== Le politiche orarie devono iniziare all'inizio dell'ora

Se si dispone di una policy SnapCenter che si ripete ogni ora, ma le ore non sono a intervalli all'inizio dell'ora, il BlueXP backup and recovery non importeranno la risorsa. Ad esempio, le policy con pianificazioni alle 1:30, 2:30, 3:30, ecc. non sono supportate, mentre le policy con pianificazioni alle 1:00, 2:00, 3:00, ecc. sono supportate.

*Soluzione alternativa*: utilizzare un criterio che si ripete a intervalli di 1 ora a partire dall'inizio dell'ora.



=== Non sono supportate le policy giornaliere e mensili associate a una risorsa

Se un criterio SnapCenter si ripete sia a intervalli giornalieri che mensili, il BlueXP backup and recovery non importeranno il criterio.

Ad esempio, non è possibile associare una policy giornaliera (con durata inferiore o uguale a 7 giorni oppure superiore a 7 giorni) a una risorsa e contemporaneamente associare una policy mensile alla stessa risorsa.

*Soluzione alternativa*: utilizzare un criterio che preveda un intervallo giornaliero o mensile, ma non entrambi.



=== Criteri di backup su richiesta non migrati

Il BlueXP backup and recovery non importano criteri di backup su richiesta da SnapCenter.



=== Criteri di backup solo log non migrati

BlueXP backup and recovery non importa i criteri di backup solo log da SnapCenter. Se un criterio di SnapCenter include backup solo log, BlueXP backup and recovery non importerà la risorsa.

*Soluzione alternativa*: utilizzare un criterio in SnapCenter che utilizzi più dei semplici backup dei soli registri.



=== Mappatura host

SnapCenter non dispone di cluster di storage o SVM per la mappatura delle risorse sugli host, a differenza di BlueXP backup and recovery . Il cluster ONTAP o SVM locale non verrà mappato a un host nella versione Preview BlueXP backup and recovery . Inoltre, BlueXP non supporta le SVM.

*Soluzione alternativa*: prima di importare risorse da SnapCenter, creare un ambiente di lavoro in BlueXP backup and recovery per tutti i sistemi di storage ONTAP locali registrati in SnapCenter locale. Quindi, importare le risorse per quel cluster da SnapCenter in BlueXP backup and recovery.



=== Orari non a intervalli di 15 minuti

Se si dispone di una pianificazione di criteri SnapCenter che inizia a una determinata ora e si ripete ogni tot minuti, ma i minuti non sono a intervalli di 15 minuti, il BlueXP backup and recovery non importeranno la pianificazione.

*Soluzione alternativa*: utilizzare SnapCenter per modificare il criterio in modo che venga ripetuto a intervalli di 15 minuti.
