---
sidebar: sidebar 
permalink: br-reference-limitations.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Le limitazioni note identificano le funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni. 
---
= Limitazioni note con il BlueXP backup and recovery per i volumi ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano funzioni non supportate da questa versione di BlueXP backup and recovery o che non interagiscono correttamente con essa. Esaminare attentamente queste limitazioni.

* Backup e recovery di BlueXP  che eseguono il backup di Cloud Volume ONTAP in un archivio di oggetti nelle aree Cina di AWS (tra cui Pechino e Ningxia); tuttavia, potrebbe essere necessario modificare manualmente le policy IAM (Identity and Access Management) prima di tutto.
+
Per informazioni dettagliate sulla creazione di un connettore in AWS, fare riferimento alla https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-bluexp.html["Installazione di un connettore in AWS"^].

+
Per ulteriori dettagli in un post su un blog, fare riferimento a https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-May-23-Updates/ba-p/444052["Blog della funzione di backup e ripristino BlueXP  - maggio 2023"^].

* Il backup e recovery di BlueXP  non supporta le aree geografiche di Microsoft Azure Cina.
+
Per informazioni dettagliate sulla creazione di un connettore in Azure, fare riferimento alla sezione https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-bluexp.html["Installazione di un connettore in Azure"^].

* Il backup e recovery di BlueXP  non supporta i backup di FlexCache Volumes.




== Limitazioni di replicazione per volumi ONTAP

* È possibile selezionare un solo volume FlexGroup alla volta per la replica. Sarà necessario attivare i backup separatamente per ogni volume FlexGroup.
+
Non esistono limiti per i volumi FlexVol: È possibile selezionare tutti i volumi FlexVol nel proprio ambiente di lavoro e assegnare le stesse policy di backup.

* Le seguenti funzionalità sono supportate in https://docs.netapp.com/us-en/bluexp-replication/index.html["Servizio di replica BlueXP"], Ma non quando si utilizza la funzionalità di replica di BlueXP backup e recovery:
+
** Non è disponibile alcun supporto per una configurazione a cascata in cui la replica avviene dal volume A al volume B e dal volume B al volume C. Il supporto include la replica dal volume A al volume B.
** Non è disponibile alcun supporto per la replica dei dati da e verso FSX per sistemi ONTAP.
** Non è disponibile alcun supporto per la creazione di una replica singola di un volume.


* Quando si creano repliche da sistemi ONTAP on-premise, se la versione di ONTAP sul sistema Cloud Volumes ONTAP di destinazione è 9.8, 9.9 o 9.11, sono consentiti solo i criteri del vault mirror.




== Limitazioni del backup su oggetto per i volumi ONTAP

* Durante il backup dei dati, il backup e il ripristino di BlueXP  non manterrà la crittografia del volume NetApp (NVE). Ciò significa che i dati crittografati sul volume NVE verranno decrittografati mentre i dati vengono trasferiti alla destinazione e la crittografia non verrà mantenuta.
+
Per una spiegazione su questi tipi di crittografia, fare riferimento a https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["Panoramica sulla configurazione di NetApp Volume Encryption"^].



* Se gli snapshot di conservazione a lungo termine sono abilitati su un volume di destinazione SnapMirror utilizzando la pianificazione nel criterio SnapMirror, gli snapshot vengono creati direttamente sul volume di destinazione. In questo caso, non è consigliabile eseguire il backup di tali volumi utilizzando il backup e recovery di BlueXP , poiché tali snapshot non verranno spostate nello storage a oggetti.
* Durante il backup dei dati, il backup e il ripristino di BlueXP  non manterrà la crittografia del volume NetApp (NVE). Ciò significa che i dati crittografati sul volume NVE verranno decrittografati mentre i dati vengono trasferiti alla destinazione e la crittografia non verrà mantenuta.
+
Per una spiegazione su questi tipi di crittografia, fare riferimento a https://docs.netapp.com/us-en/ontap/encryption-at-rest/configure-netapp-volume-encryption-concept.html["Panoramica sulla configurazione di NetApp Volume Encryption"^].



* Se gli snapshot di conservazione a lungo termine sono abilitati su un volume di destinazione SnapMirror utilizzando la pianificazione nel criterio SnapMirror, gli snapshot vengono creati direttamente sul volume di destinazione. In questo caso, non è consigliabile eseguire il backup di tali volumi utilizzando il backup e recovery di BlueXP , poiché tali snapshot non verranno spostate nello storage a oggetti.
* Quando si crea o modifica un criterio di backup quando al criterio non sono assegnati volumi, il numero di backup conservati può essere massimo di 1018. Dopo aver assegnato i volumi al criterio, è possibile modificare il criterio per creare fino a 4000 backup.
* Quando si esegue il backup dei volumi di protezione dei dati (DP):
+
** Relazioni con le etichette SnapMirror `app_consistent` e. `all_source_snapshot` non verrà eseguito il backup nel cloud.
** Se si creano copie locali di Snapshot sul volume di destinazione di SnapMirror (indipendentemente dalle etichette di SnapMirror utilizzate), queste istantanee non verranno spostate nel cloud come backup. A questo punto, è necessario creare una policy Snapshot con le etichette desiderate nel volume DP di origine per eseguire il backup di BlueXP e il ripristino.


* I backup dei volumi FlexGroup non possono essere spostati nello storage di archiviazione.
* I backup dei volumi FlexGroup possono utilizzare la protezione DataLock e ransomware se il cluster esegue ONTAP 9.13.1 o superiore.
* Il backup del volume SVM-DR è supportato con le seguenti restrizioni:
+
** I backup sono supportati solo dal secondario ONTAP.
** Il criterio Snapshot applicato al volume deve essere uno dei criteri riconosciuti dal backup e ripristino BlueXP, inclusi quelli giornalieri, settimanali, mensili e così via Il criterio predefinito "SM_created" (utilizzato per *Mirror All Snapshots*) non viene riconosciuto e il volume DP non viene visualizzato nell'elenco dei volumi di cui è possibile eseguire il backup.
** Le soluzioni SVM-DR e backup e recovery dei volumi funzionano in maniera completamente indipendente quando viene eseguito il backup dall'origine o dalla destinazione. L'unica restrizione è che SVM-DR non replica la relazione cloud di SnapMirror. Nello scenario di disaster recovery, quando le SVM vanno online nel luogo secondario, devi aggiornare manualmente la relazione al cloud di SnapMirror.




* Supporto MetroCluster:
+
** Quando si utilizza ONTAP 9.12.1 GA o versione successiva, il backup è supportato quando è collegato al sistema primario. L'intera configurazione di backup viene trasferita al sistema secondario in modo che i backup nel cloud continuino automaticamente dopo lo switchover. Non è necessario configurare il backup sul sistema secondario (in realtà, non è necessario farlo).
** Quando si utilizza ONTAP 9.12.0 e versioni precedenti, il backup è supportato solo dal sistema secondario ONTAP.
** Al momento non sono supportati i backup dei volumi FlexGroup.


* Il backup del volume ad-hoc con il pulsante *Backup Now* non è supportato sui volumi di protezione dei dati.
* Le configurazioni SM-BC non sono supportate.
* ONTAP non supporta la fan-out delle relazioni di SnapMirror da un singolo volume a più archivi di oggetti; pertanto, questa configurazione non è supportata dal backup e ripristino di BlueXP.
* La modalità WORM/Compliance in un archivio di oggetti è attualmente supportata su Amazon S3, Azure e StorageGRID. Questa funzione è nota come funzionalità DataLock e deve essere gestita utilizzando le impostazioni di backup e ripristino di BlueXP e non l'interfaccia del provider cloud.




== Limitazioni di ripristino per i volumi ONTAP

Queste limitazioni si applicano sia ai metodi Search & Restore che Browse & Restore per il ripristino di file e cartelle, a meno che non venga espressamente indicato.

* Browse & Restore consente di ripristinare fino a 100 singoli file alla volta.
* Search & Restore può ripristinare 1 file alla volta.
* Quando si utilizza ONTAP 9.13.0 o versione successiva, Sfoglia e ripristina e Cerca e ripristina una cartella con tutti i file e le sottocartelle al suo interno.
+
Quando si utilizza una versione di ONTAP superiore alla 9.11.1 ma precedente alla 9.13.0, l'operazione di ripristino consente di ripristinare solo la cartella selezionata e i file contenuti in tale cartella, senza ripristinare le sottocartelle o i file contenuti nelle sottocartelle.

+
Quando si utilizza una versione di ONTAP precedente alla 9.11.1, il ripristino delle cartelle non è supportato.

* Il ripristino di directory/cartelle è supportato per i dati che risiedono nello storage di archiviazione solo quando il cluster esegue ONTAP 9.13.1 e versioni successive.
* Il ripristino di directory/cartelle è supportato per i dati protetti mediante DataLock solo quando il cluster esegue ONTAP 9.13.1 e versioni successive.
* Il ripristino di directory/cartelle non è attualmente supportato da repliche e/o snapshot locali.
* Il ripristino da volumi FlexGroup a volumi FlexVol o da volumi FlexVol a volumi FlexGroup non è supportato.
* Il file da ripristinare deve utilizzare la stessa lingua del volume di destinazione. Se le lingue non sono uguali, viene visualizzato un messaggio di errore.
* La priorità di ripristino _alta_ non è supportata quando si ripristinano i dati dallo storage di archivio Azure ai sistemi StorageGRID.
* Se si effettua il backup di un volume DP e si decide di interrompere la relazione di SnapMirror in quel volume, non sarà possibile ripristinare i file in quel volume a meno che non si elimini anche la relazione di SnapMirror o si inverta la direzione di SnapMirror.
* Limitazioni del ripristino rapido:
+
** La posizione di destinazione deve essere un sistema Cloud Volumes ONTAP che utilizzi ONTAP 9.13.0 o versioni successive.
** Non è supportato con i backup che si trovano nell'archivio.
** I volumi FlexGroup sono supportati solo se il sistema di origine da cui è stato creato il backup cloud eseguiva ONTAP 9.12.1 o versione successiva.
** I volumi SnapLock sono supportati solo se il sistema di origine da cui è stato creato il backup cloud eseguiva ONTAP 9.11.0 o versione successiva.



