---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: bluexp, backup, back up, restore, recovery, aws, azure 
summary: Prima di utilizzare il BlueXP backup and recovery, eseguire alcuni passaggi per impostare le destinazioni di backup. 
---
= Imposta le destinazioni di backup prima di utilizzare il BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Prima di utilizzare il BlueXP backup and recovery, eseguire alcuni passaggi per impostare le destinazioni di backup.

Prima di iniziare, verificare link:concept-start-prereq.html["prerequisiti"]che l'ambiente sia pronto.



== Preparare la destinazione di backup

Preparare una o più delle seguenti destinazioni di backup:

* NetApp StorageGRID.
+
Fare riferimento alla https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Scopri StorageGRID"^].

+
Fare riferimento a https://docs.netapp.com/us-en/storagegrid/index.html["Documentazione StorageGRID"^] per i dettagli su StorageGRID.

* Servizi Web di Amazon. Fare riferimento alla https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["Documentazione di Amazon S3"^].
+
Per preparare AWS come destinazione di backup, procedi come segue:

+
** Configurare un account in AWS.
** Configurare le autorizzazioni S3 in AWS, elencate nella sezione successiva.
** Per informazioni dettagliate sulla gestione dello storage AWS in BlueXP , fare riferimento alla https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Gestisci i bucket Amazon S3"^].




* Microsoft Azure.
+
** Fare riferimento alla https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html["Documentazione Azure NetApp Files"^].
** Configurare un account in Azure.
** Configurare  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Autorizzazioni Azure"^] in Azzurro.
** Per informazioni dettagliate sulla gestione dell'archiviazione di Azure in BlueXP, fare riferimento a  https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Gestione degli account storage Azure"^] .




Dopo aver configurato le opzioni nella destinazione di backup stessa, sarà possibile configurarla in seguito come destinazione di backup nel servizio BlueXP backup and recovery . Per informazioni dettagliate su come configurare la destinazione di backup nel BlueXP backup and recovery, fare riferimento a link:br-start-discover-backup-targets.html["Scopri le destinazioni di backup"] .



== Impostare le autorizzazioni S3

Dovrai configurare due set di autorizzazioni AWS S3:

* Permessi per il connettore per creare e gestire il bucket S3.
* Autorizzazioni per il cluster ONTAP on-premise in modo che possa leggere e scrivere i dati nel bucket S3.


.Fasi
. Assicurarsi che il connettore disponga delle autorizzazioni necessarie. Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["Autorizzazioni dei criteri BlueXP "].
+

NOTE: Quando si creano backup nelle regioni AWS China, è necessario modificare il nome risorsa AWS "arn" in tutte le sezioni _Resource_ delle policy IAM da "aws" a "aws-cn", ad esempio `arn:aws-cn:s3:::netapp-backup-*`.

. Quando si attiva il servizio, la procedura guidata di backup richiede di inserire una chiave di accesso e una chiave segreta. Queste credenziali vengono passate al cluster ONTAP in modo che ONTAP possa eseguire il backup e il ripristino dei dati nel bucket S3. A tale scopo, è necessario creare un utente IAM con le seguenti autorizzazioni.
+
Fare riferimento a. https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Documentazione AWS: Creazione di un ruolo per delegare le autorizzazioni a un utente IAM"^].

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

