---
sidebar: sidebar 
permalink: br-use-protect-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, snapcenter 
summary: 'Il BlueXP backup and recovery consentono di gestire le informazioni sull"host del carico di lavoro, le informazioni sul database e le informazioni sulle istanze. È possibile visualizzare, modificare ed eliminare le impostazioni di protezione per l"inventario.' 
---
= Aggiungi e proteggi le applicazioni Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il BlueXP backup and recovery consentono di individuare facilmente i cluster Kubernetes, senza dover generare e caricare file kubeconfig. È possibile connettere i cluster Kubernetes e installare il software necessario utilizzando semplici comandi copiati dall'interfaccia utente BlueXP .

.Ruolo BlueXP richiesto
Amministratore dell'organizzazione o amministratore SnapCenter . link:reference-roles.html["Scopri di più sui ruoli di accesso BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Scopri i ruoli di accesso BlueXP per tutti i servizi"^] .



== Aggiungi e proteggi una nuova applicazione Kubernetes

Il primo passo per proteggere le applicazioni Kubernetes è creare un'applicazione all'interno BlueXP backup and recovery. Quando si crea un'applicazione, si segnala a BlueXP l'applicazione in esecuzione sul cluster Kubernetes.

.Prima di iniziare
Prima di poter aggiungere e proteggere un'applicazione Kubernetes, è necessario link:br-start-discover.html["scopri i carichi di lavoro di Kubernetes"] .

.Fasi
. Nel BlueXP backup and recovery, seleziona *Inventario*.
. Scegli un'istanza di Kubernetes e seleziona *Visualizza* per visualizzare le risorse associate a tale istanza.
. Selezionare la scheda *Applicazioni*.
. Selezionare *Crea applicazione*.
. Inserisci un nome per l'applicazione.
. Facoltativamente, seleziona uno dei seguenti campi per cercare le risorse che desideri proteggere:
+
** Cluster associato
** Spazi dei nomi associati
** Tipi di risorse
** Selettori di etichette


. Facoltativamente, seleziona *Risorse con ambito cluster* per scegliere tutte le risorse con ambito a livello di cluster. Se le includi, verranno aggiunte all'applicazione al momento della creazione.
. Facoltativamente, seleziona *Cerca* per trovare le risorse in base ai tuoi criteri di ricerca.
+

NOTE: BlueXP non memorizza i parametri o i risultati della ricerca; i parametri vengono utilizzati per cercare nel cluster Kubernetes selezionato le risorse che possono essere incluse nell'applicazione.

. BlueXP visualizza un elenco di risorse che corrispondono ai criteri di ricerca.
. Se l'elenco contiene le risorse che desideri proteggere, seleziona *Avanti*.
. Facoltativamente, nell'area *Criterio*, seleziona un criterio di protezione esistente per proteggere l'applicazione o creane uno nuovo. Se non selezioni un criterio, l'applicazione verrà creata senza criterio di protezione. Puoi aggiungerne uno in seguito.
. Nell'area *Prescript e postscript*, abilitare e configurare eventuali hook di esecuzione prescript o postscript che si desidera eseguire prima o dopo le operazioni di backup. Per abilitare prescript o postscript, è necessario aver già creato almeno uno. link:br-use-manage-execution-hook-templates.html["modello di gancio di esecuzione"] .
. Selezionare *Crea*.


.Risultato
L'applicazione viene creata e visualizzata nell'elenco delle applicazioni nella scheda *Applicazioni* dell'inventario di Kubernetes. BlueXP abilita la protezione dell'applicazione in base alle impostazioni e puoi monitorarne l'avanzamento nell'area *Monitoraggio* di backup e ripristino.



== Proteggere un'applicazione Kubernetes esistente

Abilita un criterio di protezione su un'applicazione Kubernetes che hai già aggiunto.

.Fasi
. Nel BlueXP backup and recovery, seleziona *Inventario*.
. Scegli un'istanza di Kubernetes e seleziona *Visualizza* per visualizzare le risorse associate a tale istanza.
. Selezionare la scheda *Applicazioni*.
. Nell'elenco delle applicazioni, seleziona l'applicazione che desideri proteggere e seleziona il menu Azioni associato.
. Selezionare *Proteggi*.
. Nell'area *Criterio*, seleziona un criterio di protezione esistente per proteggere l'applicazione oppure creane uno nuovo.
. Nell'area *Prescript e postscript*, abilita e configura eventuali hook di esecuzione prescript o postscript che desideri eseguire prima o dopo le operazioni di backup. Puoi configurare il tipo di hook di esecuzione, il modello utilizzato, gli argomenti e i selettori di etichetta.
. Selezionare *fine*.


.Risultato
BlueXP abilita la protezione per l'applicazione in base alle impostazioni, ed è possibile monitorarne l'avanzamento nell'area *Monitoraggio* di backup e ripristino. Non appena si abilita la protezione per un'applicazione, BlueXP ne crea un backup completo. Eventuali backup incrementali futuri vengono creati in base alla pianificazione definita nella policy di protezione associata all'applicazione.



== Esegui subito il backup di un'applicazione Kubernetes

Crea manualmente un backup di un'applicazione Kubernetes per stabilire una base di riferimento per backup e snapshot futuri o per garantire la protezione dei dati più recenti.

.Fasi
. Nel BlueXP backup and recovery, seleziona *Inventario*.
. Scegli un'istanza di Kubernetes e seleziona *Visualizza* per visualizzare le risorse associate a tale istanza.
. Selezionare la scheda *Applicazioni*.
. Nell'elenco delle applicazioni, seleziona l'applicazione di cui vuoi effettuare il backup e seleziona il menu Azioni associato.
. Selezionare *Esegui backup adesso*.
. Assicurarsi che sia selezionato il nome corretto dell'applicazione.
. Selezionare *Backup*.


.Risultato
BlueXP crea un backup dell'applicazione e ne visualizza l'avanzamento nell'area *Monitoraggio* di backup e ripristino. Il backup viene creato in base ai criteri di protezione associati all'applicazione.
