---
sidebar: sidebar 
permalink: br-use-mssql-restore-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: 'I backup dei dati sono disponibili per il ripristino dalle posizioni in cui sono stati creati, inclusi snapshot, repliche e backup nell"archiviazione di oggetti. Esamina le posizioni di origine del ripristino, i punti di ripristino e i tipi di risorse da ripristinare.' 
---
= Ripristina la panoramica dei carichi di lavoro di Microsoft SQL utilizzando il BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I backup dei dati di Microsoft SQL Server ottenuti tramite BlueXP backup and recovery sono disponibili per il ripristino dalle posizioni in cui sono stati spostati: snapshot, repliche o backup nell'archiviazione di oggetti. È possibile ripristinare un carico di lavoro nell'ambiente di lavoro originale, in un ambiente di lavoro diverso che utilizza lo stesso account cloud o in un sistema ONTAP locale. Verificare le posizioni di origine del ripristino, i punti di ripristino e i tipi di risorse da ripristinare.

.Ripristina da queste posizioni
È possibile ripristinare i carichi di lavoro da diverse posizioni di partenza:

* Ripristina da una posizione primaria
* Ripristina da una risorsa replicata
* Ripristina da un backup dell'archivio oggetti


.Ripristinare questi punti
È possibile ripristinare i dati all'ultimo snapshot o a questi punti:

* Ripristina da snapshot
* Ripristina fino a un punto specifico nel tempo. Questo è utile se si conoscono il nome e la posizione del file, nonché la data dell'ultima volta in cui era in buone condizioni.
* Ripristina l'ultimo backup




== Cosa succederà

Per i dettagli su come ripristinare i carichi di lavoro, vedere link:br-use-mssql-restore.html["Ripristinare i carichi di lavoro"] .
