---
sidebar: sidebar 
permalink: concept-clone-cloud-native-oracle-concepts.html 
keywords: cloud-native application data, clone, Cloud Manager, BlueXP, Oracle database, Oracle, clone limitations, clone methods, clone naming scheme, requirements, clone specification file 
summary: Comprendere i concetti dei cloni prima di clonare il database. 
---
= Clonare concetti e requisiti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile clonare un database Oracle residente su Amazon FSX per NetApp ONTAP o Cloud Volumes ONTAP utilizzando il backup del database sull'host del database di origine o su un host alternativo. È possibile clonare il backup dai sistemi di storage primari.

Prima di clonare il database, è necessario comprendere i concetti dei cloni e assicurarsi che tutti i requisiti siano soddisfatti.



== Requisiti per la clonazione di un database Oracle

Prima di clonare un database Oracle, è necessario assicurarsi che i prerequisiti siano stati completati.

* Dovrebbe essere stato creato un backup del database. La creazione dei dati online e il backup dei log dovrebbero essere stati effettuati correttamente per consentire l'esecuzione dell'operazione di cloning.
* Nel parametro asm_diskstring, configurare:
+
** AFD:* se si utilizza ASMFD
** ORCL:* se si utilizza ASMLIB
** /Dev/<exact_device_location> se si utilizza ASMUDEV


* Se si crea il clone su un host alternativo, l'host alternativo deve soddisfare i seguenti requisiti:
+
** Il plug-in deve essere installato sull'host alternativo.
** Il software Oracle deve essere installato sull'host alternativo.
** L'host clone dovrebbe essere in grado di rilevare LUN dallo storage se si clonano database che risiedono su storage SAN iSCSI. Se si esegue la clonazione su un host alternativo, assicurarsi che sia stata stabilita una sessione iSCSI tra lo storage e l'host alternativo.
** Se il database di origine è un database ASM:
+
*** L'istanza di ASM deve essere attiva e in esecuzione sull'host in cui verrà eseguito il clone.
*** Il provisioning del gruppo di dischi ASM deve essere eseguito prima dell'operazione di clonazione se si desidera inserire i file di log di archiviazione del database clonato in un gruppo di dischi ASM dedicato.
*** Il nome del gruppo di dischi dati può essere configurato, ma assicurarsi che il nome non sia utilizzato da altri gruppi di dischi ASM sull'host in cui verrà eseguito il clone.
*** I file di dati che risiedono sul gruppo di dischi ASM vengono forniti come parte del flusso di lavoro dei cloni.








== Limitazioni

* La clonazione dei database residenti su Azure NetApp Files non è supportata.
* La clonazione dei database residenti su Qtree non è supportata.
* Il backup di un database clonato non è supportato.
* Se su Amazon FSX per NetApp ONTAP sono attivati backup automatici giornalieri, i volumi clonati su Amazon FSX per NetApp ONTAP non possono essere cancellati dall'interfaccia utente di BlueXP perché FSX avrebbe creato backup sui volumi clonati.
È necessario eliminare i volumi clonati dopo aver eliminato tutti i backup del volume dall'interfaccia utente FSX e quindi eliminare i cloni dall'interfaccia utente BlueXP utilizzando l'opzione force.




== Metodi di clonazione

È possibile creare un clone utilizzando il metodo di base o il file di specifica del clone.



=== Clonare utilizzando il metodo di base

È possibile creare il clone con le configurazioni predefinite in base al database di origine e al backup selezionato.

* I parametri del database, home e utente del sistema operativo vengono impostati per impostazione predefinita sul database di origine.
* I percorsi dei file di dati vengono denominati in base allo schema di denominazione selezionato.
* Non è possibile specificare le istruzioni pre-script, post-script e SQL.
* Per impostazione predefinita, l'opzione di ripristino è *fino all'annullamento* e utilizza il backup del registro associato al backup dei dati per il ripristino




=== Clonare utilizzando il file delle specifiche

È possibile definire le configurazioni nel file di specifica del clone e utilizzarlo per clonare il database. È possibile scaricare il file delle specifiche, modificarlo in base alle proprie esigenze e quindi caricarlo. link:task-clone-cloud-native-oracle-data.html["Scopri di più"].

I diversi parametri definiti nel file delle specifiche e modificabili sono i seguenti:

|===
| Parametro | Descrizione 


 a| 
control_files
 a| 
Posizione dei file di controllo per il database clone.

Il numero di file di controllo sarà lo stesso del database di origine. Se si desidera eseguire l'override del percorso del file di controllo, è possibile specificare un percorso diverso del file di controllo. Il file system o il gruppo di dischi ASM dovrebbe esistere sull'host.



 a| 
redo_logs
 a| 
Posizione, dimensione, numero di gruppi di ripristino dei log di ripristino.

Per clonare il database sono necessari almeno due gruppi di log di ripristino. Se si desidera eseguire l'override del percorso del file di log di ripristino, è possibile personalizzare il percorso del file di log di ripristino in un file system diverso da quello del database di origine.il file system o il gruppo di dischi ASM dovrebbe esistere sull'host.



 a| 
versione_oracle
 a| 
Versione di Oracle sull'host di destinazione.



 a| 
oracle_home
 a| 
Oracle home sull'host di destinazione.



 a| 
enable_archive_log_mode
 a| 
Controlla la modalità del log di archiviazione per il database clone



 a| 
parametri_database
 a| 
Parametri del database per il database clonato



 a| 
istruzioni_sql
 a| 
Le istruzioni SQL da eseguire sul database dopo la clonazione



 a| 
os_user_detail
 a| 
Utente del sistema operativo Oracle nel database dei cloni di destinazione



 a| 
porta_database
 a| 
Porta utilizzata per comunicare con il database se l'autenticazione del sistema operativo è disattivata sull'host.



 a| 
porta_asm
 a| 
Porta utilizzata per la comunicazione con il database ASM se le credenziali sono fornite nell'input create clone.



 a| 
skip_recovery
 a| 
Non esegue l'operazione di recovery.



 a| 
fino a scn
 a| 
Recupera il database fino al numero scn (System Change Number) specificato.



 a| 
fino a_ora
 a| 
Recupera il database fino alla data e all'ora specificate.

Il formato accettato è _mm/gg/aaaa hh:mm:ss_.



 a| 
until_cancel
 a| 
Effettua il ripristino montando il backup del log associato al backup dei dati selezionato per la clonazione.

Il database clonato viene recuperato fino a quando il file di log non è mancante o corrotto.



 a| 
log_paths
 a| 
Posizioni aggiuntive dei percorsi dei log di archiviazione da utilizzare per il ripristino del database clonato.



 a| 
source_location
 a| 
Posizione del gruppo di dischi o del punto di montaggio sull'host del database di origine.



 a| 
clone_location
 a| 
Posizione del gruppo di dischi o del punto di montaggio che deve essere creato sull'host di destinazione corrispondente alla posizione di origine.



 a| 
location_type
 a| 
Può essere ASM_diskgroup o mountpoint.

I valori vengono compilati automaticamente al momento del download del file. Non modificare questo parametro.



 a| 
pre_script
 a| 
Script da eseguire sull'host di destinazione prima di creare il clone.



 a| 
post_script
 a| 
Script da eseguire sull'host di destinazione dopo la creazione del clone.



 a| 
percorso
 a| 
Percorso assoluto dello script sull'host clone.

Lo script deve essere memorizzato in /var/opt/snapcenter/spl/scripts o in qualsiasi cartella all'interno di questo percorso.



 a| 
timeout
 a| 
Il tempo di timeout specificato per lo script in esecuzione sull'host di destinazione.



 a| 
argomenti
 a| 
Argomenti specificati per gli script.

|===


== Schema di naming dei cloni

Lo schema di naming dei cloni definisce la posizione dei punti di montaggio e il nome dei diskgroup del database clonato. È possibile selezionare *identico* o *generato automaticamente*.



=== Schema di denominazione identico

Se si seleziona lo schema di denominazione dei cloni come *identico*, la posizione dei punti di montaggio e il nome dei diskgroup del database clonato saranno gli stessi del database di origine.

Ad esempio, se il punto di montaggio del database di origine è _/netapp_sourcedb/data_1 , +DATA1_DG_, per il database clonato il punto di montaggio rimane lo stesso sia per NFS che per ASM su SAN.

* Le configurazioni come il numero e il percorso dei file di controllo e dei file di ripristino saranno le stesse dell'origine.
+

NOTE: Se i log di ripristino o i percorsi dei file di controllo si trovano nei volumi non dati, l'utente deve aver eseguito il provisioning del gruppo di dischi ASM o del punto di montaggio nell'host di destinazione.

* L'utente del sistema operativo Oracle e la versione di Oracle saranno le stesse del database di origine.
* Il nome del volume di storage clone avrà il seguente formato sourceVolNameSCS_Clone_CurrentTimeStampNumber.
+
Ad esempio, se il nome del volume nel database di origine è _sourceVolName_, il nome del volume clonato sarà _sourceVolNameSCS_Clone_1661420020304608825_.

+

NOTE: Il campo _CurrentTimeStampNumber_ fornisce l'univocità nel nome del volume.





=== Schema di naming generato automaticamente

Se si seleziona lo schema di cloning come *generato automaticamente*, alla posizione dei punti di montaggio e al nome dei diskgroup del database clonato verrà aggiunto un suffisso.

* Se è stato selezionato il metodo di clone di base, il suffisso sarà *Clone SID*.
* Se è stato selezionato il metodo del file delle specifiche, il suffisso sarà il suffisso *suffisso* specificato durante il download del file delle specifiche del clone.


Ad esempio, se il punto di montaggio del database di origine è _/netapp_sourcedb/data_1_ e il *Clone SID* o il *suffisso* è _HR_, il punto di montaggio del database clonato sarà _/netapp_sourcedb/data_1_HR_.

* Il numero di file di controllo e di log di ripristino sarà uguale a quello dell'origine.
* Tutti i file di log di ripristino e i file di controllo si trovano su uno dei punti di montaggio dati clonati o su gruppi di dischi ASM di dati.
* Il nome del volume di storage clone avrà il seguente formato sourceVolNameSCS_Clone_CurrentTimeStampNumber.
+
Ad esempio, se il nome del volume nel database di origine è _sourceVolName_, il nome del volume clonato sarà _sourceVolNameSCS_Clone_1661420020304608825_.

+

NOTE: Il campo _CurrentTimeStampNumber_ fornisce l'univocità nel nome del volume.

* Il formato del punto di montaggio NAS sarà _SourceNASMountPoint_suffix_.
* Il formato del gruppo di dischi ASM sarà _SourceDiskgroup_suffix_.
+

NOTE: Se il numero di caratteri nel gruppo di dischi clone è maggiore di 25, il numero di caratteri nel gruppo sarà _SC_hashCode_suffix_.





== Parametri del database

Il valore dei seguenti parametri di database sarà uguale a quello del database di origine, indipendentemente dallo schema di denominazione dei cloni.

* log_archive_format
* audit_trail
* processi
* destinazione_aggregato_pga
* remote_login_passwordfile
* undo_tablespace
* open_cursors
* sga_target
* db_block_size


Al valore dei seguenti parametri di database viene aggiunto un suffisso basato sul SID clone.

* audit_file_dest = {sourcedatabase_parametervalue}_suffix
* log_archive_dest_1 = {sourcedatabase_oraclehome}_suffix




== Variabili di ambiente predefinite supportate per il clone specifico prespt e postscript

È possibile utilizzare le variabili di ambiente predefinite supportate quando si eseguono prespt e postscript durante la clonazione di un database.

* SC_ORIGINAL_SID specifica il SID del database di origine. Questo parametro verrà popolato per i volumi dell'applicazione. Esempio: NFSB32
* SC_ORIGINAL_HOST specifica il nome dell'host di origine. Questo parametro verrà popolato per i volumi dell'applicazione. Esempio: asmrac1.gdl.englab.netapp.com
* SC_ORACLE_HOME specifica il percorso della home directory Oracle del database di destinazione. Esempio: /Ora01/app/oracle/product/18.1.0/db_1
* SC_BACKUP_NAME specifica il nome del backup. Questo parametro verrà popolato per i volumi dell'applicazione. Esempi:
+
** Se il database non è in esecuzione in modalità ARCHIVELOG: DATA@RG2_scspr2417819002_07-20- 2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
** Se il database è in esecuzione in modalità ARCHIVELOG: DATA@RG2_scspr2417819002_07-20- 2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20- 2021_12.16.48.9267_1,RG2_scspr2417819002_07-21- 2021_12.16.48.9267_07 12.16.48.9267_22_2021


* SC_ORIGINAL_OS_USER specifica il proprietario del sistema operativo del database di origine. Esempio: oracle
* SC_ORIGINAL_OS_GROUP specifica il gruppo del sistema operativo del database di origine. Esempio: Oinstall
* SC_TARGET_SID specifica il SID del database clonato. Per il flusso di lavoro del clone PDB, il valore di questo parametro non sarà predefinito. Questo parametro verrà popolato per i volumi dell'applicazione. Esempio: Clonedb
* SC_TARGET_HOST specifica il nome dell'host in cui verrà clonato il database. Questo parametro verrà popolato per i volumi dell'applicazione. Esempio: asmrac1.gdl.englab.netapp.com
* SC_TARGET_OS_USER specifica il proprietario del sistema operativo del database clonato. Per il flusso di lavoro del clone PDB, il valore di questo parametro non sarà predefinito. Esempio: oracle
* SC_TARGET_OS_GROUP specifica il gruppo di sistemi operativi del database clonato. Per il flusso di lavoro del clone PDB, il valore di questo parametro non sarà predefinito. Esempio: Oinstall
* SC_TARGET_DB_PORT specifica la porta del database clonato. Per il flusso di lavoro del clone PDB, il valore di questo parametro non sarà predefinito. Esempio: 1521




=== Delimitatori supportati

* @ viene utilizzato per separare i dati dal nome del database e per separare il valore dalla chiave. Esempio: DATI@RG2_scspr2417819002_07-20- 2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
* | viene utilizzato per separare i dati tra due entità diverse per il parametro SC_BACKUP_NAME. Esempio: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
* , viene utilizzato per separare un insieme di variabili per la stessa chiave. Esempio: DATI@RG2_scspr2417819002_07-20- 2021_12.16.48.9267_0|LOG@RG2_scspr2417819002_07-20- 2021_12.16.48.9267_1,RG2_scspr2417819002_07-21- 2021_12.16.48.9267_1,RG2_scspr2417819002_07-22-2021_12.16.48.9267_1

