---
sidebar: sidebar 
permalink: prev-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteggi i tuoi carichi di lavoro VMware con il BlueXP backup and recovery NetApp BlueXP. 
---
= Protezione dei carichi di lavoro delle macchine virtuali nella panoramica BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteggi i carichi di lavoro delle tue macchine virtuali con il BlueXP backup and recovery. Il BlueXP backup and recovery offrono operazioni di backup e ripristino rapide, efficienti in termini di spazio, coerenti con gli arresti anomali e con la VM per VM, datastore e VMDK.

È possibile eseguire il backup dei datastore su Amazon Web Services S3, Microsoft Azure Blob, piattaforma cloud Google e StorageGRID e ripristinare le macchine virtuali nel plug-in SnapCenter on-premise per l'host VMware vSphere.

[]
====
*NOTA* Per passare da e verso i carichi di lavoro BlueXP backup and recovery , fare riferimento a link:br-start-switch-ui.html["Passa a diversi carichi di lavoro BlueXP backup and recovery"] .

====
Per istruzioni sulla protezione dei carichi di lavoro delle macchine virtuali, vedere i seguenti argomenti:

* link:prev-vmware-policy-create.html["Creare una policy per i carichi di lavoro VMware"]
* link:prev-vmware-backup-aws.html["Eseguire il backup dei datastore VMware su Amazon Web Services"]
* link:prev-vmware-backup-azure.html["Eseguire il backup dei datastore VMware su Microsoft Azure"]
* link:prev-vmware-backup-gcp.html["Esegui il backup dei datastore VMware su Google Cloud Platform"]
* link:prev-vmware-backup-storagegrid.html["Eseguire il backup dei datastore VMware su StorageGRID"]
* link:prev-vmware-restore.html["Ripristinare i carichi di lavoro VMware"]
* link:prev-vmware-manage.html["Gestisci la protezione per i carichi di lavoro VMware"]

