---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteggi i tuoi carichi di lavoro VMware con il BlueXP backup and recovery NetApp BlueXP. 
---
= Registra il SnapCenter Plug-in for VMware vSphere da utilizzare con il BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario registrare il plug-in SnapCenter per l'host VMware vSphere nel backup e ripristino BlueXP affinché i datastore e le macchine virtuali vengano visualizzati. Solo un utente con accesso amministrativo può registrare il plug-in SnapCenter per l'host VMware vSphere.

[]
====
*NOTA* Per passare da e verso i carichi di lavoro BlueXP backup and recovery , fare riferimento a link:br-start-switch-ui.html["Passa a diversi carichi di lavoro BlueXP backup and recovery"] .

====
.Fasi
. Nell'interfaccia utente BlueXP , seleziona *Protezione* > *Backup e ripristino* > *Macchine virtuali*.
. Dal menu a discesa *Impostazioni*, seleziona * SnapCenter Plug-in for VMware vSphere*.
. Selezionare *Registra il SnapCenter Plug-in for VMware vSphere*.
. Specificare i seguenti dettagli:
+
.. Nel campo Plug-in SnapCenter per VMware vSphere, specificare l'FQDN o l'indirizzo IP del plug-in SnapCenter per l'host VMware vSphere.
.. Nel campo porta, specificare il numero di porta su cui è in esecuzione il plug-in SnapCenter per l'host VMware vSphere.
+
Assicurarsi che la comunicazione sia aperta tra il plug-in SnapCenter on-premise per l'host VMware vSphere in esecuzione sulla porta 8144 predefinita e l'istanza del connettore BlueXP che potrebbe essere in esecuzione in qualsiasi provider cloud (servizi Web Amazon, Microsoft Azure, piattaforma cloud Google) o on-premise.

.. Nel campo Nome utente e Password, specificare le credenziali dell'utente vCenter con il ruolo di amministratore.


. Selezionare *Registra*.


*Al termine*

Selezionare *Backup e ripristino* > *Macchine virtuali* per visualizzare tutti i datastore e le macchine virtuali protetti mediante il SnapCenter Plug-in for VMware vSphere .
