---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Cloud provider
    default: Tutti i cloud provider
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documenti di backup e ripristino BlueXP
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/whats-new.html"
    - title: Limitazioni note
      url: "/reference-limitations.html"
  - title: Inizia subito
    entries:
    - title: Informazioni su backup e ripristino BlueXP
      url: "/concept-backup-to-cloud.html"
    - title: Impostare la licenza
      url: "/task-licensing-cloud-backup.html"
  - title: Monitorare la protezione dei dati
    entries:
    - title: Report sulla copertura per la data Protection
      url: "/task-report-inventory.html"
    - title: Monitorare lo stato dei processi di backup e ripristino
      url: "/task-monitor-backup-jobs.html"
  - title: Backup e ripristino dei dati ONTAP
    entries:
    - title: Proteggi i dati del tuo volume ONTAP
      url: "/concept-ontap-backup-to-cloud.html"
    - title: Pianifica il tuo percorso di protezione
      url: "/concept-protection-journey.html"
    - title: Gestire le policy per ONTAP Volumes
      url: "/task-create-policies-ontap.html"
    - title: Opzioni di policy backup su oggetti
      url: "/concept-cloud-backup-policies.html"
    - title: Gestire le opzioni di backup su oggetto in Impostazioni avanzate
      url: "/task-manage-backup-settings-ontap.html"
    - title: Eseguire il backup di Cloud Volumes ONTAP su Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: Backup di Cloud Volumes ONTAP in Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: Eseguire il backup di Cloud Volumes ONTAP su Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: Eseguire il backup on-premise di ONTAP su Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: Esegui il backup di ONTAP on-premise in Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: Eseguire il backup on-premise di ONTAP su Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: Esegui il backup da ONTAP on-premise a ONTAP S3
      url: "/task-backup-onprem-to-ontap-s3.html"
    - title: Eseguire il backup on-premise di ONTAP su StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: Gestire i backup di ONTAP
      url: "/task-manage-backups-ontap.html"
    - title: Ripristino dai backup di ONTAP
      url: "/task-restore-backups-ontap.html"
  - title: Backup e ripristino dei dati delle applicazioni on-premise
    entries:
    - title: Proteggi i dati delle tue applicazioni on-premise
      url: "/concept-protect-app-data-to-cloud.html"
    - title: Registrare il server SnapCenter
      url: "/task-register-snapcenter-server.html"
    - title: Creare un criterio per il backup delle applicazioni
      url: "/task-create-policies-apps.html"
    - title: Eseguire il backup dei dati delle applicazioni on-premise su Amazon Web
        Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: Eseguire il backup dei dati delle applicazioni on-premise su Microsoft
        Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: Eseguire il backup dei dati delle applicazioni on-premise su Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: Eseguire il backup dei dati delle applicazioni on-premise su StorageGRID
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: Gestire la protezione delle applicazioni
      url: "/task-manage-app-backups.html"
    - title: Ripristinare i dati delle applicazioni on-premise
      entries:
      - title: Ripristinare il database Oracle
        url: "/task-restore-oracle-data.html"
      - title: Ripristinare il database di SQL Server
        url: "/task-restore-sql-data.html"
      - title: Ripristinare il database SAP HANA
        url: "/task-restore-hana-backup.html"
      - title: Ripristino dei database MongoDB, MySQL e PostgreSQL
        url: "/task-restore-customplugin-backup.html"
  - title: Backup e ripristino dei dati delle macchine virtuali
    entries:
    - title: Proteggi i dati delle tue macchine virtuali
      url: "/concept-protect-vm-data.html"
    - title: Registrare il plug-in SnapCenter per l'host VMware vSphere
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: Creare una policy per il backup dei datastore
      url: "/task-create-policies-vms.html"
    - title: Eseguire il backup dei datastore su Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: Eseguire il backup dei datastore su Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: Backup dei datastore su Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: Eseguire il backup dei datastore su StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: Gestione della protezione dei dati di datastore e macchine virtuali
      url: "/task-manage-vm-data-in-cloud.html"
    - title: Ripristinare i dati delle macchine virtuali
      url: "/task-restore-vm-data.html"
  - title: Automatizza con l'API REST
    url: "/api-backup-restore.html"
  - title: Riferimento
    entries:
    - title: Tier di storage di archivio AWS supportati
      url: "/reference-aws-backup-tiers.html"
    - title: Tier di accesso all'archivio Azure supportati
      url: "/reference-azure-backup-tiers.html"
    - title: Tier di storage di archivio supportati da Google
      url: "/reference-google-backup-tiers.html"
    - title: Configurare il backup per l'accesso multi-account in Azure
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: Ripristinare il database di backup e ripristino BlueXP in un sito buio
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: Riavviare il backup e il ripristino di BlueXP
      url: "/reference-restart-backup.html"
  - title: Conoscenza e supporto
    entries:
    - title: Registrati per ricevere assistenza
      url: "/task-support-registration.html"
    - title: Richiedi assistenza
      url: "/task-get-help.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
