---
sidebar: sidebar 
permalink: reference-configure-azure-netapp-files.html 
keywords: Cloud Manager, Azure NetApp Files, working environment, Connector, BlueXP 
summary: 'Creare l"ambiente di lavoro Azure NetApp Files e il connettore' 
---
= Configurare Azure NetApp Files
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con BlueXP è necessario creare un ambiente di lavoro Azure NetApp Files per aggiungere e gestire volumi e servizi dati aggiuntivi. È inoltre necessario creare un connettore in Azure che consenta a BlueXP di gestire risorse e processi all'interno del proprio ambiente di cloud pubblico.



== Creare un ambiente di lavoro Azure NetApp Files

È necessario creare ambienti di lavoro Azure NetApp Files in cui sono ospitati i database. Per ulteriori informazioni, fare riferimento a. link:https://docs.netapp.com/us-en/bluexp-azure-netapp-files/concept-azure-netapp-files.html["Scopri di più su Azure NetApp Files"] e. link:https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-create-working-env.html["Creare un ambiente di lavoro Azure NetApp Files"].



== Creare un connettore

Un amministratore di account BlueXP dovrebbe implementare un connettore in Azure che consenta a BlueXP di gestire risorse e processi all'interno del tuo ambiente di cloud pubblico.

Per ulteriori informazioni, fare riferimento a. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-creating-connectors-azure.html["Creare un connettore in Azure da BlueXP"].

* Assicurarsi che vi sia connettività tra il connettore e gli host del database.
* Se si dispone dell'ambiente di lavoro e dei database Azure NetApp Files nella stessa rete virtuale (VNET), è possibile implementare il connettore nella stessa rete virtuale.
* Se si dispone di un ambiente di lavoro Azure NetApp Files e di database in reti VNet diverse e si hanno carichi di lavoro NAS (NFS) configurati su Azure NetApp Files, è possibile creare il connettore su una delle reti VNet.


Dopo aver creato il connettore, aggiungere l'ambiente di lavoro facendo clic su *Storage* > *Canvas* > *My Working Environments* > *Add Working Environment*.
