---
sidebar: sidebar 
permalink: reference-backup-cbs-db-in-dark-site.html 
keywords: backup database, recover database, dark site, private mode, restore database, backup and recovery, BlueXP Connector 
summary: 'Quando si utilizza il BlueXP backup and recovery in un sito senza accesso a Internet, noto come "modalità privata", i dati di configurazione BlueXP backup and recovery vengono sottoposti a backup nel bucket StorageGRID o ONTAP S3 in cui vengono archiviati i backup.  Se in futuro si verifica un problema con il sistema host di BlueXP Connector, è possibile distribuire un nuovo Connector e ripristinare i dati critici BlueXP backup and recovery .' 
---
= Ripristinare i dati di configurazione BlueXP backup and recovery in un sito oscuro
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si utilizza il BlueXP backup and recovery in un sito senza accesso a Internet, noto come _modalità privata_, i dati di configurazione BlueXP backup and recovery vengono sottoposti a backup nel bucket StorageGRID o ONTAP S3 in cui vengono archiviati i backup.  In caso di problemi con il sistema host di BlueXP Connector, è possibile distribuire un nuovo Connector e ripristinare i dati critici BlueXP backup and recovery .


NOTE: Questa procedura si applica solo ai dati di volume ONTAP .

Quando si utilizza il BlueXP backup and recovery in un ambiente SaaS in cui BlueXP Connector è distribuito presso il provider cloud o sul proprio sistema host con accesso a Internet, tutti i dati importanti di configurazione BlueXP backup and recovery vengono sottoposti a backup e protetti nel cloud.  Se riscontri un problema con il connettore, crea semplicemente un nuovo connettore e aggiungi i tuoi ambienti di lavoro: i dettagli del backup verranno ripristinati automaticamente.

Esistono due tipi di dati sottoposti a backup:

* Database BlueXP backup and recovery : contiene un elenco di tutti i volumi, file di backup, criteri di backup e informazioni di configurazione.
* File di catalogo indicizzati: contengono indici dettagliati utilizzati per la funzionalità di ricerca e ripristino, che rendono le ricerche molto rapide ed efficienti quando si cercano dati di volume che si desidera ripristinare.


Questi dati vengono sottoposti a backup una volta al giorno a mezzanotte e vengono conservate al massimo 7 copie di ciascun file.  Se il connettore gestisce più ambienti di lavoro ONTAP locali, i file BlueXP backup and recovery saranno posizionati nel bucket dell'ambiente di lavoro attivato per primo.


TIP: Nessun dato di volume viene mai incluso nel database BlueXP backup and recovery o nei file del catalogo indicizzato.



== Ripristina i dati BlueXP backup and recovery su un nuovo connettore BlueXP

Se il tuo BlueXP Connector locale subisce un errore catastrofico, dovrai installare un nuovo Connector e quindi ripristinare i dati BlueXP backup and recovery sul nuovo Connector.

Per ripristinare il funzionamento del sistema BlueXP backup and recovery, è necessario eseguire le seguenti operazioni:

* Installa un nuovo connettore BlueXP
* Ripristinare il database BlueXP backup and recovery
* Ripristina i file del catalogo indicizzato
* Riscopri tutti i tuoi sistemi ONTAP on-premise e i sistemi StorageGRID nell'interfaccia utente BlueXP


Una volta verificato che il sistema è tornato a funzionare, ti consigliamo di creare nuovi file di backup.

.Cosa ti servirà
Sarà necessario accedere ai backup più recenti del database e dell'indice dal bucket StorageGRID o ONTAP S3 in cui sono archiviati i file di backup:

* File di database MySQL BlueXP backup and recovery
+
Questo file si trova nella seguente posizione nel bucket `netapp-backup-<GUID>/mysql_backup/` , e si chiama `CBS_DB_Backup_<day>_<month>_<year>.sql` .

* File zip di backup del catalogo indicizzato
+
Questo file si trova nella seguente posizione nel bucket `netapp-backup-<GUID>/catalog_backup/` , e si chiama `Indexed_Catalog_DB_Backup_<db_name>_<day>_<month>_<year>.zip` .





=== Installa un nuovo connettore su un nuovo host Linux locale

Quando installi un nuovo BlueXP Connector, assicurati di scaricare la stessa versione del software installata sul Connector originale.  Le modifiche periodiche alla struttura del database BlueXP backup and recovery potrebbero rendere le nuove versioni del software incompatibili con i backup del database originali.  Puoi https://docs.netapp.com/us-en/bluexp-setup-admin/task-upgrade-connector.html["aggiornare il software Connector alla versione più recente dopo aver ripristinato il database di backup"^] .

. https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Installa BlueXP Connector su un nuovo host Linux locale"^]
. Accedi a BlueXP utilizzando le credenziali utente amministratore appena create.




=== Ripristinare il database BlueXP backup and recovery

. Copiare il backup MySQL dalla posizione di backup al nuovo host del connettore.  Di seguito utilizzeremo il nome file di esempio "CBS_DB_Backup_23_05_2023.sql".
. Copiare il backup nel contenitore Docker MySQL utilizzando uno dei seguenti comandi, a seconda che si utilizzi un contenitore Docker o Podman:
+
[source, cli]
----
docker cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
+
[source, cli]
----
podman cp CBS_DB_Backup_23_05_2023.sql ds_mysql_1:/.
----
. Accedere alla shell del contenitore MySQL utilizzando uno dei seguenti comandi, a seconda che si utilizzi un contenitore Docker o Podman:
+
[source, cli]
----
docker exec -it ds_mysql_1 sh
----
+
[source, cli]
----
podman exec -it ds_mysql_1 sh
----
. Nella shell del contenitore, distribuire "env".
. Ti servirà la password del database MySQL, quindi copia il valore della chiave "MYSQL_ROOT_PASSWORD".
. Ripristinare il BlueXP backup and recovery utilizzando il seguente comando:
+
[source, cli]
----
mysql -u root -p cloud_backup < CBS_DB_Backup_23_05_2023.sql
----
. Verificare che il BlueXP backup and recovery siano stati ripristinati correttamente utilizzando i seguenti comandi SQL:
+
[source, cli]
----
mysql -u root -p cloud_backup
----
+
Inserisci la password.

+
[source, cli]
----
mysql> show tables;
mysql> select * from volume;
----
+
Controlla se i volumi mostrati sono gli stessi presenti nell'ambiente originale.





=== Ripristina i file del catalogo indicizzato

. Copiare il file zip di backup del catalogo indicizzato (utilizzeremo il nome file di esempio "Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip") dalla posizione di backup al nuovo host del connettore nella cartella "/opt/application/netapp/cbs".
. Decomprimere il file "Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip" utilizzando il seguente comando:
+
[source, cli]
----
unzip Indexed_Catalog_DB_Backup_catalogdb1_23_05_2023.zip -d catalogdb1
----
. Eseguire il comando *ls* per assicurarsi che sia stata creata la cartella "catalogdb1" con le sottocartelle "changes" e "snapshots".




=== Scopri i tuoi cluster ONTAP e i sistemi StorageGRID

. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html#discover-clusters-using-a-connector["Scopri tutti gli ambienti di lavoro ONTAP on-prem"^]che erano disponibili nel tuo ambiente precedente.  Ciò include il sistema ONTAP utilizzato come server S3.
. https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Scopri i tuoi sistemi StorageGRID"^] .




=== Impostare i dettagli dell'ambiente StorageGRID

Aggiungere i dettagli del sistema StorageGRID associato ai propri ambienti di lavoro ONTAP così come sono stati configurati nella configurazione originale del connettore utilizzando https://docs.netapp.com/us-en/bluexp-automation/index.html["API BlueXP"^] .

Le seguenti informazioni si applicano alle installazioni in modalità privata a partire da BlueXP 3.9.xx.  Per le versioni precedenti, utilizzare la seguente procedura: https://community.netapp.com/t5/Tech-ONTAP-Blogs/DarkSite-Cloud-Backup-MySQL-and-Indexed-Catalog-Backup-and-Restore/ba-p/440800["DarkSite Cloud Backup: backup e ripristino di MySQL e catalogo indicizzato"^] .

Sarà necessario eseguire questi passaggi per ogni sistema che esegue il backup dei dati su StorageGRID.

. Estrarre il token di autorizzazione utilizzando la seguente API oauth/token.
+
[source, http]
----
curl 'http://10.193.192.202/oauth/token' -X POST -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate' -H 'Content-Type: application/json' -d '{"username":"admin@netapp.com","password":"Netapp@123","grant_type":"password"}
> '
----
+
Mentre l'indirizzo IP, il nome utente e le password sono valori personalizzati, il nome dell'account non lo è.  Il nome dell'account è sempre "account-DARKSITE1".  Inoltre, il nome utente deve essere formattato come indirizzo email.

+
Questa API restituirà una risposta simile alla seguente.  È possibile recuperare il token di autorizzazione come mostrato di seguito.

+
[source, text]
----
{"expires_in":21600,"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzM2MDIzLCJleHAiOjE2NzI3NTc2MjMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9CJtRpRDY23PokyLg1if67bmgnMcYxdCvBOY-ZUYWzhrWbbY_hqUH4T-114v_pNDsPyNDyWqHaKizThdjjHYHxm56vTz_Vdn4NqjaBDPwN9KAnC6Z88WA1cJ4WRQqj5ykODNDmrv5At_f9HHp0-xVMyHqywZ4nNFalMvAh4xESc5jfoKOZc-IOQdWm4F4LHpMzs4qFzCYthTuSKLYtqSTUrZB81-o-ipvrOqSo1iwIeHXZJJV-UsWun9daNgiYd_wX-4WWJViGEnDzzwOKfUoUoe1Fg3ch--7JFkFl-rrXDOjk1sUMumN3WHV9usp1PgBE5HAcJPrEBm0ValSZcUbiA"}
----
. Estrarre l'ID dell'ambiente di lavoro e l'X-Agent-Id utilizzando l'API tenancy/external/resource.
+
[source, http]
----
curl -X GET http://10.193.192.202/tenancy/external/resource?account=account-DARKSITE1 -H 'accept: application/json' -H 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw'
----
+
Questa API restituirà una risposta simile alla seguente.  Il valore sotto "resourceIdentifier" indica _WorkingEnvironment Id_ e il valore sotto "agentId" indica _x-agent-id_.

. Aggiornare il database BlueXP backup and recovery con i dettagli del sistema StorageGRID associato agli ambienti di lavoro.  Assicurarsi di immettere il nome di dominio completo di StorageGRID, nonché la chiave di accesso e la chiave di archiviazione come mostrato di seguito:
+
[source, http]
----
curl -X POST 'http://10.193.192.202/account/account-DARKSITE1/providers/cloudmanager_cbs/api/v1/sg/credentials/working-environment/OnPremWorkingEnvironment-pMtZND0M' \
> --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjJlMGFiZjRiIn0eyJzdWIiOiJvY2NtYXV0aHwxIiwiYXVkIjpbImh0dHBzOi8vYXBpLmNsb3VkLm5ldGFwcC5jb20iXSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vZnVsbF9uYW1lIjoiYWRtaW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbCI6ImFkbWluQG5ldGFwcC5jb20iLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIiwiaWF0IjoxNjcyNzIyNzEzLCJleHAiOjE2NzI3NDQzMTMsImlzcyI6Imh0dHA6Ly9vY2NtYXV0aDo4NDIwLyJ9X_cQF8xttD0-S7sU2uph2cdu_kN-fLWpdJJX98HODwPpVUitLcxV28_sQhuopjWobozPelNISf7KvMqcoXc5kLDyX-yE0fH9gr4XgkdswjWcNvw2rRkFzjHpWrETgfqAMkZcAukV4DHuxogHWh6-DggB1NgPZT8A_szHinud5W0HJ9c4AaT0zC-sp81GaqMahPf0KcFVyjbBL4krOewgKHGFo_7ma_4mF39B1LCj7Vc2XvUd0wCaJvDMjwp19-KbZqmmBX9vDnYp7SSxC1hHJRDStcFgJLdJHtowweNH2829KsjEGBTTcBdO8SvIDtctNH_GAxwSgMT3zUfwaOimPw' \
> --header 'x-agent-id: vB_1xShPpBtUosjD7wfBlLIhqDgIPA0wclients' \
> -d '
> { "storage-server" : "sr630ip15.rtp.eng.netapp.com:10443", "access-key": "2ZMYOAVAS5E70MCNH9", "secret-password": "uk/6ikd4LjlXQOFnzSzP/T0zR4ZQlG0w1xgWsB" }'
----




=== Verificare le impostazioni BlueXP backup and recovery

. Selezionare ciascun ambiente di lavoro ONTAP e fare clic su *Visualizza backup* accanto al servizio Backup e ripristino nel pannello di destra.
+
Dovresti essere in grado di vedere tutti i backup creati per i tuoi volumi.

. Nella Dashboard di ripristino, nella sezione Cerca e ripristina, fai clic su *Impostazioni di indicizzazione*.
+
Assicurarsi che gli ambienti di lavoro in cui era precedentemente abilitata la catalogazione indicizzata rimangano abilitati.

. Dalla pagina Cerca e ripristina, esegui alcune ricerche nel catalogo per confermare che il ripristino del catalogo indicizzato sia stato completato correttamente.

