---
sidebar: sidebar 
permalink: reference-configure-cloud-volumes-ontap.html 
keywords: Cloud Manager, Cloud Volumes ONTAP, working environment, Connector, BlueXP 
summary: 'Creare l"ambiente di lavoro Cloud Volumes ONTAP e il connettore' 
---
= Configurare Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con BlueXP è necessario creare un ambiente di lavoro Cloud Volumes ONTAP per aggiungere e gestire volumi e servizi dati aggiuntivi. È inoltre necessario creare un connettore per il proprio ambiente cloud che consenta a BlueXP di gestire risorse e processi all'interno del proprio ambiente di cloud pubblico.



== Creare un ambiente di lavoro Cloud Volumes ONTAP

È possibile individuare e aggiungere sistemi Cloud Volumes ONTAP esistenti a BlueXP. Per ulteriori informazioni, fare riferimento a. link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-adding-systems.html["Aggiunta di sistemi Cloud Volumes ONTAP esistenti a BlueXP"].



== Creare un connettore

Puoi iniziare a utilizzare Cloud Volumes ONTAP per il tuo ambiente cloud in pochi passaggi. Per ulteriori informazioni, fare riferimento a una delle seguenti voci:

* link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["Avvio rapido di Cloud Volumes ONTAP in AWS"]
* link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-azure.html["Avvio rapido di Cloud Volumes ONTAP in Azure"]
* link:https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html["Guida rapida per Cloud Volumes ONTAP in Google Cloud"]


È necessario utilizzare lo stesso connettore per gestire sia l'ambiente di lavoro Cloud Volumes ONTAP che i database.

* Se l'ambiente di lavoro Cloud Volumes ONTAP e i database si trovano nello stesso cloud privato virtuale (VPC) o VNET, è possibile implementare il connettore nello stesso VPC o VNET.
* Se si dispone di un ambiente di lavoro Cloud Volumes ONTAP e di database in VPC o VNet diversi, assicurarsi che i VPC o VNet siano peering.

