---
sidebar: sidebar 
permalink: reference-roles.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, roles, permissions, access control, role-based access control, rbac 
summary: 'Il BlueXP backup and recovery utilizzano ruoli per governare l"accesso che ogni utente ha a funzionalità e azioni specifiche' 
---
= Gestione dell'identità e dell'accesso alle funzionalità BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il BlueXP backup and recovery utilizzano la gestione dell'identità e dell'accesso (IAM) per gestire l'accesso di ciascun utente a specifiche funzionalità e azioni.

Il servizio utilizza i seguenti ruoli specifici per il BlueXP backup and recovery.

* *Super amministratore di backup e ripristino*: esegue qualsiasi azione nel BlueXP backup and recovery.
* *Amministratore di backup*: esegue backup su snapshot locali, replica su storage secondario ed esegue backup su azioni di storage di oggetti in BlueXP backup and recovery.
* *Ripristina amministrazione*: ripristina i carichi di lavoro utilizzando il BlueXP backup and recovery.
* *Clone admin*: clona applicazioni e dati utilizzando il BlueXP backup and recovery.
* *Visualizzatore di backup e ripristino*: visualizza le informazioni nel BlueXP backup and recovery, ma non esegue alcuna azione.


Per i dettagli su tutti i ruoli di accesso BlueXP , vedere  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["La documentazione di installazione e amministrazione di BlueXP"^] .

Nella tabella seguente sono indicate le azioni che ogni ruolo di BlueXP backup and recovery può eseguire.

[cols="20,20,15,15a,15a,15a"]
|===
| Funzione e azione | Super amministratore di backup e ripristino | Amministratore del backup | Ripristina amministratore | Clona amministratore | Visualizzatore 


| Aggiungi, modifica o elimina host | Sì | No  a| 
No
 a| 
No
 a| 
No



| Installa i plugin | Sì | No  a| 
No
 a| 
No
 a| 
No



| Aggiungi credenziali (host, istanza, vCenter) | Sì | No  a| 
No
 a| 
No
 a| 
No



| Visualizza dashboard e tutte le schede | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
Sì



| Inizia la prova gratuita | Sì | No  a| 
No
 a| 
No
 a| 
No



| Avvia il rilevamento dei carichi di lavoro | No | Sì  a| 
Sì
 a| 
Sì
 a| 
No



| Visualizza le informazioni sulla licenza | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
Sì



| Attiva la licenza | Sì | No  a| 
No
 a| 
No
 a| 
No



| Visualizza gli host | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
Sì



6+| *Orari*: 


| Attivare gli orari | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
No



| Sospendi gli orari | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
No



6+| *Politiche e protezione*: 


| Visualizza i piani di protezione | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
Sì



| Crea, modifica o elimina la protezione | Sì | Sì  a| 
No
 a| 
No
 a| 
No



| Ripristinare i carichi di lavoro | Sì | No  a| 
Sì
 a| 
No
 a| 
No



| Crea un clone, dividi un clone o elimina un clone | Sì | No  a| 
No
 a| 
Sì
 a| 
No



| Crea, modifica o elimina una policy | Sì | Sì  a| 
No
 a| 
No
 a| 
No



6+| *Segnalazioni*: 


| Visualizzare i report | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
Sì



| Creare report | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
No



| Eliminare i referti | Sì | No  a| 
No
 a| 
No
 a| 
No



6+| *Importa da SnapCenter e gestisci l'host*: 


| Visualizza i dati SnapCenter importati | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
Sì



| Importa dati da SnapCenter | Sì | Sì  a| 
No
 a| 
No
 a| 
No



| Gestisci (migra) l'host | Sì | Sì  a| 
No
 a| 
No
 a| 
No



6+| *Configura impostazioni*: 


| Configurare la directory del registro | Sì | Sì  a| 
Sì
 a| 
No
 a| 
No



| Associa o rimuovi le credenziali dell'istanza | Sì | Sì  a| 
Sì
 a| 
No
 a| 
No



6+| *Secchi*: 


| Visualizza bucket | Sì | Sì  a| 
Sì
 a| 
Sì
 a| 
Sì



| Crea, modifica o elimina bucket | Sì | Sì  a| 
No
 a| 
No
 a| 
No

|===