---
sidebar: sidebar 
permalink: task-restore-sql-data.html 
keywords: restore, Azure, Amazon Web services, Microsoft SQL Server database 
summary: È possibile ripristinare il database SQL Server dal cloud al server SnapCenter on-premise. 
---
= Ripristinare il database di SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile ripristinare il database di SQL Server nella posizione originale o nella posizione alternativa.


NOTE: Single file Restore (SFR), Recovery of log backups e reseed of Availability group non sono supportati.

.Fasi
. Nell'interfaccia utente di BlueXP, fare clic su *Protection* > *Backup and Recovery* > *Applications*.
. Nel campo *Filtra per*, selezionare il filtro *tipo* e dal menu a discesa selezionare *SQL*.
. Fare clic su *View Details* (Visualizza dettagli) per visualizzare tutti i backup disponibili.
. Selezionare il backup e fare clic su *Restore* (Ripristina).
. Nella pagina delle opzioni di ripristino, specificare la posizione in cui si desidera ripristinare i file di database.
+
|===
| Se... | Eseguire questa operazione... 


 a| 
Ripristinare la posizione originale
 a| 
.. Selezionare *Restore to original location* (Ripristina posizione originale).
.. Se lo snapshot si trova nello storage di archiviazione, selezionare la priorità per ripristinare i dati dallo storage di archiviazione.
.. Fare clic su *Avanti*.




 a| 
Ripristinare temporaneamente in un altro storage e copiare i file ripristinati nella posizione originale
 a| 
.. Selezionare *Restore to original location* (Ripristina posizione originale).
.. Se lo snapshot si trova nello storage di archiviazione, selezionare la priorità per ripristinare i dati dallo storage di archiviazione.
.. Selezionare *Modifica posizione di storage*.
+
Se si seleziona *Modifica posizione di memorizzazione*, è possibile aggiungere un suffisso al volume di destinazione. Se la casella di controllo non è stata selezionata, per impostazione predefinita *_restore* viene aggiunto al volume di destinazione.

.. Fare clic su *Avanti*.
.. Nella pagina Storage mapping, specificare i dettagli della posizione di storage alternativa in cui i dati ripristinati dall'archivio di oggetti verranno memorizzati temporaneamente.
.. Fare clic su *Avanti*.




 a| 
Ripristinare in una posizione alternativa
 a| 
.. Selezionare *Ripristina in una posizione alternativa*.
.. Se lo snapshot si trova nello storage di archiviazione, selezionare la priorità per ripristinare i dati dallo storage di archiviazione.
.. Fare clic su *Avanti*.
.. Nella pagina host di destinazione, selezionare un nome host, specificare un nome di database (facoltativo), selezionare un'istanza e specificare i percorsi di ripristino.
+

NOTE: L'estensione del file fornita nel percorso alternativo deve essere uguale all'estensione del file di database originale.

.. Fare clic su *Avanti*.




 a| 
Ripristinare temporaneamente in un altro storage e copiare i file ripristinati nella posizione alternativa
 a| 
.. Selezionare *Ripristina in una posizione alternativa*.
.. Se lo snapshot si trova nello storage di archiviazione, selezionare la priorità per ripristinare i dati dallo storage di archiviazione.
.. Selezionare *Modifica posizione di storage*.
+
Se si seleziona *Modifica posizione di memorizzazione*, è possibile aggiungere un suffisso al volume di destinazione. Se la casella di controllo non è stata selezionata, per impostazione predefinita *_restore* viene aggiunto al volume di destinazione.

.. Fare clic su *Avanti*.
.. Nella pagina Storage mapping, specificare i dettagli della posizione di storage alternativa in cui i dati ripristinati dall'archivio di oggetti verranno memorizzati temporaneamente.
.. Fare clic su *Avanti*.
.. Nella pagina host di destinazione, selezionare un nome host, specificare un nome di database (facoltativo), selezionare un'istanza e specificare i percorsi di ripristino.
+

NOTE: L'estensione del file fornita nel percorso alternativo deve essere uguale all'estensione del file di database originale.

.. Fare clic su *Avanti*.


|===
. Nell'opzione *Pre-Operations*, selezionare una delle seguenti opzioni:
+
** Selezionare *sovrascrivere il database con lo stesso nome durante il ripristino* per ripristinare il database con lo stesso nome.
** Selezionare *Mantieni impostazioni di replica del database SQL* per ripristinare il database e conservare le impostazioni di replica esistenti.


. Nella sezione *Post-Operations*, per specificare lo stato del database per il ripristino di registri transazionali aggiuntivi, selezionare una delle seguenti opzioni:
+
** Selezionare *operativo, ma non disponibile* se si stanno ripristinando tutti i backup necessari.
+
Questo è il comportamento predefinito, che lascia il database pronto per l'uso eseguendo il rollback delle transazioni non assegnate. Non è possibile ripristinare ulteriori registri delle transazioni fino a quando non si crea un backup.

** Selezionare *non operativo, ma disponibile* per lasciare il database non operativo senza eseguire il rollback delle transazioni non assegnate.
+
È possibile ripristinare ulteriori registri delle transazioni. Non è possibile utilizzare il database fino a quando non viene ripristinato.

** Selezionare *Read-only mode (modalità di sola lettura) e Available* (disponibile) per lasciare il database in modalità di sola lettura.
+
Questa opzione annulla le transazioni non assegnate, ma salva le azioni non riuscite in un file di standby in modo che gli effetti di ripristino possano essere ripristinati.

+
Se l'opzione Undo directory (Annulla directory) è attivata, vengono ripristinati altri log delle transazioni. Se l'operazione di ripristino del log delle transazioni non riesce, è possibile eseguire il rollback delle modifiche. La documentazione di SQL Server contiene ulteriori informazioni.



. Fare clic su *Avanti*.
. Esaminare i dettagli e fare clic su *Restore* (Ripristina).

