---
sidebar: sidebar 
permalink: task-restore-customplugin-backup.html 
keywords: restore, mount application backups, MongoDB, MySQL, PostgreSQL 
summary: Puoi ripristinare il database SAP HANA dal cloud al server SnapCenter on-premise. 
---
= Ripristino dei database MongoDB, MySQL e PostgreSQL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile ripristinare i database MongoDB, MySQL e PostgreSQL su qualsiasi host.

*Fasi*

. Nell'interfaccia utente di BlueXP, fare clic su *Protection* > *Backup and Recovery* > *Applications*.
. Nel campo *Filtra per*, seleziona il filtro *tipo* e dal menu a discesa seleziona *MongoDB*, *MySQL* o *PostgreSQL*.
. Fare clic su *View Details* (Visualizza dettagli) corrispondente al database che si desidera ripristinare e fare clic su *Restore* (Ripristina).
. Nella pagina delle opzioni di ripristino, specificare una delle seguenti opzioni:
+
.. Per l'ambiente NAS, specificare l'FQDN o l'indirizzo IP dell'host su cui esportare i volumi ripristinati dall'archivio di oggetti.
.. Per l'ambiente SAN, specificare gli iniziatori dell'host a cui mappare le LUN dei volumi ripristinati dall'archivio di oggetti.


. Se lo snapshot si trova nello storage di archiviazione, selezionare la priorità per ripristinare i dati dallo storage di archiviazione.
. Se lo spazio disponibile sullo storage di origine non è sufficiente o se lo storage di origine non è disponibile, selezionare *Modifica ubicazione dello storage*.
+
Se si seleziona *Modifica posizione di memorizzazione*, è possibile aggiungere un suffisso al volume di destinazione. Se la casella di controllo non è stata selezionata, per impostazione predefinita *_restore* viene aggiunto al volume di destinazione.

. Fare clic su *Avanti*.
. Nella pagina Storage mapping, specificare i dettagli della posizione di storage alternativa in cui verranno memorizzati i dati ripristinati dall'archivio di oggetti.
. Fare clic su *Avanti*.
. Esaminare i dettagli e fare clic su *Restore* (Ripristina).


Questa operazione esegue solo l'esportazione dello storage del backup selezionato sull'host specificato. Si consiglia di montare manualmente il file system e di visualizzare il database. Dopo aver utilizzato il volume, l'amministratore dello storage può eliminare il volume dal cluster ONTAP.


NOTE: Se l'operazione di ripristino non viene completata, non tentare di eseguire nuovamente il processo di ripristino finché Job Monitor non indica che l'operazione di ripristino non è riuscita. Se si tenta di eseguire nuovamente il processo di ripristino prima che Job Monitor indichi che l'operazione di ripristino non è riuscita, l'operazione di ripristino non verrà eseguita nuovamente. Quando lo stato di Job Monitor viene visualizzato come "Failed" (non riuscito), è possibile provare nuovamente il processo di ripristino.
