---
sidebar: sidebar 
permalink: task-licensing-cloud-backup.html 
keywords: license, licensing, updating license, paygo license, byol license, nlf, license generator, backup license, add backup license, update backup license, annual 
summary: Puoi concedere in licenza il backup e il recovery BlueXP acquistando un abbonamento al mercato annuale o pay-as-you-go dal tuo cloud provider o acquistando una licenza Bring-your-own da NetApp. È necessaria una licenza valida per attivare il backup e ripristino BlueXP in un ambiente di lavoro, per creare backup dei dati di produzione e per ripristinare i dati di backup in un sistema di produzione. 
---
= Impostare le licenze per il backup e ripristino BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi concedere in licenza il backup e il ripristino BlueXP acquistando un abbonamento al mercato annuale o pay-as-you-go (PAYGO) dal tuo cloud provider oppure acquistando una licenza Bring-Your-Own (BYOL) da NetApp. È necessaria una licenza valida per attivare il backup e ripristino BlueXP in un ambiente di lavoro, per creare backup dei dati di produzione e per ripristinare i dati di backup in un sistema di produzione.

Alcune note prima di leggere ulteriori informazioni:

* Se hai già sottoscritto l'abbonamento pay-as-you-go (PAYGO) nel mercato del tuo cloud provider per un sistema Cloud Volumes ONTAP, sarai automaticamente iscritto anche al backup e ripristino BlueXP. Non dovrai più iscriverti.
* Il BYOL (Bring Your Own License) di backup e recovery di BlueXP  è una licenza mobile che puoi utilizzare su tutti i sistemi associati alla tua organizzazione o account BlueXP . Quindi, se si dispone di una capacità di backup sufficiente da una licenza BYOL esistente, non sarà necessario acquistare un'altra licenza BYOL.
* Se si utilizza una licenza BYOL, si consiglia di sottoscrivere anche un abbonamento PAYGO. Se si esegue il backup di un numero di dati superiore a quello consentito dalla licenza BYOL, o se la durata della licenza scade, il backup prosegue con l'abbonamento pay-as-you-go, senza interruzioni del servizio.
* Quando si esegue il backup dei dati ONTAP on-premise su StorageGRID, è necessaria una licenza BYOL, ma lo spazio di storage del cloud provider non costa.


link:concept-ontap-backup-to-cloud.html#cost["Scopri di più sui costi legati all'utilizzo del backup e ripristino BlueXP."]



== 30 giorni di prova gratuita

Se ti iscrivi a un abbonamento pay-as-you-go nel marketplace del tuo cloud provider, è disponibile una prova gratuita di 30 giorni di backup e recovery BlueXP. La versione di prova gratuita inizia dal momento in cui ti iscrivi al marketplace listing. Nota: Se paghi per l'iscrizione al marketplace durante l'implementazione di un sistema Cloud Volumes ONTAP e poi avvia la prova gratuita di backup e recovery di BlueXP 10 giorni dopo, avrai 20 giorni rimanenti per utilizzare la prova gratuita.

Al termine della prova gratuita, potrai passare automaticamente all'abbonamento PAYGO senza interruzioni. Se decidi di non continuare a utilizzare il backup e il ripristino BlueXP, basta link:task-manage-backups-ontap.html#unregister-bluexp-backup-and-recovery-for-a-working-environment["Annullare la registrazione del backup e ripristino BlueXP dall'ambiente di lavoro"] prima della fine della prova, non ti verrà addebitato alcun costo.



== Utilizza un abbonamento A PAYGO per il backup e ripristino BlueXP

Per il pay-as-you-go, pagherai il tuo cloud provider per i costi dello storage a oggetti e per le licenze di backup NetApp su base oraria in un singolo abbonamento. È necessario iscriversi anche se si dispone di una versione di prova gratuita o se si porta la propria licenza (BYOL):

* L'iscrizione garantisce che il servizio non subisca interruzioni al termine della prova gratuita. Al termine della prova, ti verrà addebitato ogni ora in base alla quantità di dati di cui hai effettuato il backup.
* Se effettui il backup di più dati di quanto consentito dalla licenza BYOL, le operazioni di backup e ripristino dei dati proseguiranno con l'abbonamento pay-as-you-go. Ad esempio, se si dispone di una licenza 10 TIB BYOL, tutta la capacità oltre la 10 TIB viene addebitata tramite l'abbonamento PAYGO.


Non ti verrà addebitato alcun costo dal tuo abbonamento pay-as-you-go durante la prova gratuita o se non hai superato la licenza BYOL.

Esistono alcuni piani PAYGO per il backup e il ripristino BlueXP:

* Un pacchetto di "backup cloud" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP on-premise.
* Un pacchetto "CVO Professional" che consente di unire backup e ripristino di Cloud Volumes ONTAP e BlueXP. Sono inclusi backup illimitati per il sistema Cloud Volumes ONTAP che utilizza la licenza (la capacità di backup non viene conteggiata rispetto alla capacità concessa in licenza). Questa opzione non consente di eseguire il backup dei dati ONTAP on-premise.
+
Questa opzione richiede anche un abbonamento PAYGO di backup e recovery, ma non verranno addebitati costi per i sistemi Cloud Volumes ONTAP idonei.



https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#capacity-based-licensing["Scopri di più su questi pacchetti di licenza basati sulla capacità"].

Utilizza questi link per iscriverti al backup e ripristino BlueXP dal tuo mercato di cloud provider:

ifdef::aws[]

* AWS: https://aws.amazon.com/marketplace/pp/prodview-oorxakq6lq7m4["Per informazioni sui prezzi, consulta l'offerta BlueXP Marketplace"^].


endif::aws[]

ifdef::azure[]

* Azure: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-manager?tab=Overview["Per informazioni sui prezzi, consulta l'offerta BlueXP Marketplace"^].


endif::azure[]

ifdef::gcp[]

* Google Cloud: https://console.cloud.google.com/marketplace/details/netapp-cloudmanager/cloud-manager?supportedpurview=project["Per informazioni sui prezzi, consulta l'offerta BlueXP Marketplace"^].


endif::gcp[]



== Utilizzare un contratto annuale

Pagare il backup e il ripristino BlueXP ogni anno acquistando un contratto annuale. Sono disponibili in termini di 1, 2 o 3 anni.

Se si dispone di un contratto annuale da un marketplace, tutti i consumi di backup e recovery di BlueXP vengono addebitati a fronte di tale contratto. Non puoi combinare un contratto di mercato annuale con un BYOL.

ifdef::aws[]

Quando si utilizza AWS, sono disponibili due contratti annuali da https://aws.amazon.com/marketplace/pp/prodview-q7dg6zwszplri["Pagina AWS Marketplace"^] Per i sistemi Cloud Volumes ONTAP e ONTAP on-premise:

* Un piano di "backup sul cloud" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP on-premise.
+
Se si desidera utilizzare questa opzione, impostare l'abbonamento dalla pagina Marketplace, quindi https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-aws-accounts.html#associate-an-aws-subscription["Associare l'abbonamento alle credenziali AWS"^]. È inoltre necessario pagare i sistemi Cloud Volumes ONTAP utilizzando questo abbonamento annuale, in quanto è possibile assegnare un solo abbonamento attivo alle credenziali AWS in BlueXP.

* Un piano "CVO Professional" che consente di unire backup e ripristino di Cloud Volumes ONTAP e BlueXP. Sono inclusi backup illimitati per il sistema Cloud Volumes ONTAP che utilizza la licenza (la capacità di backup non viene conteggiata rispetto alla capacità concessa in licenza). Questa opzione non consente di eseguire il backup dei dati ONTAP on-premise.
+
Vedere https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Argomento relativo alle licenze Cloud Volumes ONTAP"^] per ulteriori informazioni su questa opzione di licenza.

+
Se si desidera utilizzare questa opzione, è possibile impostare il contratto annuale quando si crea un ambiente di lavoro Cloud Volumes ONTAP e BlueXP richiede di iscriversi al marketplace AWS.



endif::aws[]

ifdef::azure[]

Quando si utilizza Azure, sono disponibili due contratti annuali da https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.netapp-bluexp["Pagina del marketplace di Azure"^] Per i sistemi Cloud Volumes ONTAP e ONTAP on-premise:

* Un piano di "backup sul cloud" che consente di eseguire il backup dei dati Cloud Volumes ONTAP e dei dati ONTAP on-premise.
+
Se si desidera utilizzare questa opzione, impostare l'abbonamento dalla pagina Marketplace, quindi https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-azure-accounts.html#subscribe["Associare l'iscrizione alle credenziali Azure"^]. Nota: Dovrai anche pagare per i tuoi sistemi Cloud Volumes ONTAP utilizzando questo abbonamento di contratto annuale, poiché puoi assegnare solo un abbonamento attivo alle tue credenziali Azure in BlueXP.

* Un piano "CVO Professional" che consente di unire backup e ripristino di Cloud Volumes ONTAP e BlueXP. Sono inclusi backup illimitati per il sistema Cloud Volumes ONTAP che utilizza la licenza (la capacità di backup non viene conteggiata rispetto alla capacità concessa in licenza). Questa opzione non consente di eseguire il backup dei dati ONTAP on-premise.
+
Vedere https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Argomento relativo alle licenze Cloud Volumes ONTAP"^] per ulteriori informazioni su questa opzione di licenza.

+
Se vuoi utilizzare questa opzione, puoi impostare un contratto annuale quando crei un ambiente di lavoro Cloud Volumes ONTAP e BlueXP ti richiede di iscriverti ad Azure Marketplace.



endif::azure[]

ifdef::gcp[]

Quando si utilizza GCP, contattare il rappresentante commerciale NetApp per acquistare un contratto annuale. Il contratto è disponibile come offerta privata in Google Cloud Marketplace.

Una volta che NetApp condivide l'offerta privata con te, puoi selezionare il piano annuale quando ti iscrivi da Google Cloud Marketplace durante l'attivazione del backup e ripristino BlueXP.

endif::gcp[]



== Utilizzare una licenza BYOL di backup e ripristino BlueXP

Le licenze Bring-Your-Own di NetApp offrono termini di 1, 2 o 3 anni. Si paga solo per i dati protetti, calcolati in base alla capacità logica utilizzata (_prima_ eventuali efficienze) dei volumi ONTAP di origine di cui viene eseguito il backup. Questa capacità è nota anche come terabyte front-end (FETB).

La licenza di backup e recovery BYOL BlueXP  è una licenza mobile, in cui la capacità totale viene condivisa tra tutti i sistemi associati alla tua organizzazione o account BlueXP . Per i sistemi ONTAP, è possibile ottenere una stima approssimativa della capacità necessaria eseguendo il comando CLI per i volumi di cui si intende eseguire `volume show -fields logical-used-by-afs` il backup.

Se non si dispone di una licenza BYOL di backup e ripristino BlueXP, fare clic sull'icona della chat nell'angolo inferiore destro di BlueXP per acquistarne una.

Se si dispone di una licenza basata su nodo non assegnata per Cloud Volumes ONTAP che non si intende utilizzare, è possibile convertirla in una licenza di backup e ripristino BlueXP con la stessa equivalenza in dollari e la stessa data di scadenza. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-manage-node-licenses.html#exchange-unassigned-node-based-licenses["Fai clic qui per ulteriori informazioni"^].

Il portafoglio digitale BlueXP consente di gestire le licenze BYOL. È possibile aggiungere nuove licenze, aggiornare le licenze esistenti e visualizzare lo stato della licenza dal portafoglio digitale BlueXP.

https://docs.netapp.com/us-en/bluexp-digital-wallet/task-manage-data-services-licenses.html["Scopri come aggiungere licenze con il Digital Wallet"^].
