---
sidebar: sidebar 
permalink: task-create-policies-apps.html 
keywords: policy, create, pre-canned polices, custom policies, protection policies 
summary: 'Creare policy personalizzate per proteggere l"applicazione.' 
---
= Creare un criterio per il backup delle applicazioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario creare una policy per eseguire il backup dei dati dell'applicazione nel cloud.

.Prima di iniziare
* Se si desidera spostare i backup dall'archivio di oggetti allo storage di archiviazione, assicurarsi di utilizzare la versione di ONTAP richiesta.
+
** Se utilizzi i servizi Web Amazon, dovresti utilizzare ONTAP 9.10.1 o versione successiva
** Se si utilizza Microsoft Azure, è necessario utilizzare ONTAP 9.10.1 o versione successiva
** Se utilizzi Google Cloud, dovresti utilizzare ONTAP 9.12.1 o versione successiva


* È necessario configurare il Tier di accesso all'archivio per ciascun provider di cloud.


.Fasi
. Nell'interfaccia utente di BlueXP, fare clic su *Protection* > *Backup and Recovery* > *Applications*.
. Dal menu a discesa Impostazioni, fare clic su *Criteri* > *Crea policy*.
. Nella sezione Dettagli policy, specificare il nome del policy.
. Nella sezione conservazione, selezionare uno dei tipi di conservazione e specificare il numero di backup da conservare.
. Selezionare Primary (principale) o Secondary (secondario) come origine dello storage di backup.
. (Facoltativo) se si desidera spostare i backup dall'archivio di oggetti allo storage di archiviazione dopo un certo numero di giorni per l'ottimizzazione dei costi, selezionare la casella di controllo *Tier backups to Archival*.
. Fare clic su *Create* (Crea).
+

NOTE: Non è possibile modificare o eliminare un criterio associato a un'applicazione.


