---
sidebar: sidebar 
permalink: task-report-inventory.html 
keywords: cloud backup, backup and recovery service, backup and recovery, backup, restore, report, inventory 
summary: 'Con i report di backup e ripristino BlueXP, puoi garantire che i dati critici siano protetti in base alle policy definite dalla tua organizzazione e supportare in modo efficiente i processi di audit per la conformità. Con il report dell"inventario di backup, è possibile visualizzare tutti i backup di un account, un ambiente di lavoro o un inventario SVM specifico.' 
---
= Report sulla copertura per la data Protection
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Con i report di backup e ripristino BlueXP, puoi garantire che i dati critici siano protetti in base alle policy definite dalla tua organizzazione e fornire audit per le esigenze di conformità.

I report di backup e ripristino di BlueXP consentono di ottenere i seguenti risultati:

* *Visibilità delle operazioni*: Monitorate i vostri contratti di livello di servizio per quanto riguarda la protezione dei dati, il tasso di successo del backup e l'allineamento delle finestre di backup alle esigenze aziendali.
* *Compliance e auditing*: Utilizza report operativi e di inventario nei tuoi processi di audit interni ed esterni per il monitoraggio continuo della conformità.



NOTE: Le attività dei report vengono monitorate nel registro Job Monitoring in modo da poter controllare tutte le attività. link:task-monitor-backup-jobs.html["Scopri di più sul monitoraggio dei processi"].



== Ambito dei report

I report di backup e ripristino di BlueXP forniscono informazioni sui seguenti aspetti:

* *Posizione del connettore*: On-premise o nel cloud
* *Origine*: Volumi Cloud Volumes ONTAP, volumi ONTAP on-premise, applicazioni o volumi persistenti Kubernetes
* *Destinazione*: Qualsiasi provider cloud, NetApp StorageGRID o ONTAP S3
* *Versioni ONTAP*: 9.13.0




== Creare un report sull'inventario di backup

Dalla scheda Backup and Recovery Reports di BlueXP, è possibile creare il report Backup Inventory e filtrarne il contenuto. Il report Backup Inventory consente di visualizzare tutti i backup di un account, un ambiente di lavoro o un inventario SVM specifico.

Il report Backup Inventory mostra le seguenti informazioni e molto altro ancora:

* Account, ambiente di lavoro e SVM
* Volumi protetti e non protetti
* Destinazione del backup
* Policy di backup applicata
* Stile di crittografia (chiave gestita dal provider o chiave gestita dall'utente)
* Stato di protezione di DataLock e ransomware (governance, compliance o nessuno)
* Stato di archiviazione abilitato
* Numero di copie di backup
* Tipo di backup (backup ad-hoc pianificato o avviato dall'utente)
* Classe di storage
* Etichetta Snapshot



NOTE: Il report Backup Inventory non include informazioni di backup scadute o non riuscite.

La parte superiore del report include un grafico che mostra le seguenti informazioni:

* Numero di volumi nell'ambito con almeno un backup
* Totale di volumi inattivi più volumi attivi


Il report Backup Inventory mostra i seguenti grafici:

* *Volume backup status* (Stato backup volume): Mostra i volumi protetti rispetto ai volumi non protetti per l'ambito selezionato.
* *Volumi per numero di backup*: Raggruppa i volumi in base al numero di copie di backup disponibili per questo volume.


.Fasi
. Dal menu in alto, selezionare *Report*.
. Selezionare *Backup Inventory*.
. Selezionare *Crea report*.
. Selezionare l'account, l'ambiente di lavoro e SVM.
+

TIP: È possibile selezionare più ambienti di lavoro e SVM.

. Selezionare l'intervallo di tempo: Ultime 24 ore, settimana o mese.
. (Facoltativo) Filtra i risultati in base allo stato del lavoro.
. (Facoltativo) esportare il contenuto del report in formato .CSV selezionando *Download CSV*.




== Creare un report attività processo protezione dati

Il monitoraggio proattivo può ridurre gli sforzi necessari per monitorare tutte le risorse del tuo ecosistema. A partire da ONTAP 9.13.0, il report attività di protezione dei dati fornisce informazioni sulle operazioni di snapshot, backup, cloning e ripristino che è possibile utilizzare con il monitoraggio SLA e con i tassi di backup e ripristino.

Il report si applica alle operazioni di backup e recovery di BlueXP per Cloud Volumes ONTAP, on-premise, applicazioni e Kubernetes.

Il report Data Protection Job Activity mostra le seguenti informazioni e molto altro ancora:

* Account, ambiente di lavoro e SVM
* Tipo di lavoro (backup o ripristino)
* Nome risorsa (volume o applicazione)
* Stato del lavoro
* Orari e durata di inizio e fine
* Nome del criterio per i processi di backup
* Etichetta Snapshot per i processi di backup


I grafici nella parte superiore della pagina mostrano le seguenti informazioni:

* Lavori per tipo
+
** Numero di processi di backup e ripristino dei volumi ONTAP
** Numero di processi di backup e ripristino delle applicazioni
** Numero di processi di backup e ripristino delle macchine virtuali
** Numero di processi di backup e ripristino Kubernetes


* Attività lavorativa giornaliera


.Fasi
. Dal menu in alto, selezionare *Report*.
. Selezionare *attività di lavoro Data Protection*.
. Selezionare *Crea report*.
. Selezionare l'account, l'ambiente di lavoro e SVM.
. Selezionare l'intervallo di tempo: Ultime 24 ore, settimana o mese.
. (Facoltativo) filtrare i risultati in base allo stato del lavoro, ai tipi di lavoro (backup o ripristino) e alle risorse.
. (Facoltativo) esportare il contenuto del report in formato .CSV selezionando *Download CSV*.

