---
sidebar: sidebar 
permalink: task-restore-cloud-native-sql-data.html 
keywords: restore, SQL database, BlueXP 
summary: È possibile ripristinare il database SQL dal cloud allo stesso host. 
---
= Ripristinare il database Microsoft SQL Server
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile ripristinare il database Microsoft SQL Server sullo stesso host. È necessario prima ottenere l'elenco dei database e poi ripristinare il database.



== Visualizzare l'elenco dei database

È possibile eseguire questa API per visualizzare l'elenco dei database.

"OTTIENI snapcenter.cloudmanager.cloud.netapp.com/api/mssql/databases'

Per ulteriori informazioni, fare riferimento a: https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Databases/GetMSSQLDatabasesRequest[]



=== Risposta

Se l'API viene eseguita correttamente, viene visualizzato il codice di risposta 200.

Esempio:

[listing]
----
{
    "num_records": 3,
    "total_records": 3,
    "records": [
        {
            "id": "348901e5-aeaa-419f-88b1-80240de3b1fe",
            "name": "DB4",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.078125,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "User",
            "recovery_mode": "Full"
        },
        {
            "id": "c79d33ab-7322-4ed6-92f5-51ad7a6944e0",
            "name": "DB5",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.078125,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "User",
            "recovery_mode": "Full"
        },
        {
            "id": "40d6f35a-f4fb-48bc-8e0a-0ac93ddf0888",
            "name": "model",
            "hostname": "scspa2722211001.rtp.openenglab.netapp.com",
            "size": 0.015625,
            "instance_id": "454c8413-5351-41fc-88bf-f20fb050ec87",
            "instance": "scspa2722211001\\NAMEDINSTANCE1",
            "db_status": "Normal",
            "db_access": "eUndefined",
            "db_type": "System",
            "recovery_mode": "Full"
        }
    ],
    "_links": {
        "next": {}
    }
}
----


== Ripristinare e ripristinare il database MSSQL

È possibile eseguire questa API per ripristinare il database MSSQL.

"POST snapcenter.cloudmanager.cloud.netapp.com/api/mssql/databases/{id}/restore'

Dove _id_ è l'ID del database MSSQL ottenuto eseguendo l'API del database di visualizzazione. Per ulteriori informazioni, fare riferimento a. <<Visualizzare l'elenco dei database>>.

Per ulteriori informazioni, fare riferimento a: https://snapcenter.cloudmanager.cloud.netapp.com/api-doc/#/MSSQL%20Database%20Restore/RestoreMSSQLDatabaseRequest[]

Questa API crea un lavoro che può essere monitorato dalla scheda *Job Monitor* nell'interfaccia utente di BlueXP.



=== Parametri

|===
| Nome | Tipo | Obbligatorio 


 a| 
id_backup
 a| 
stringa
 a| 
Vero



 a| 
sovrascrivi_database
 a| 
bool
 a| 
Vero



 a| 
retain_replication_settings
 a| 
bool
 a| 
Falso



 a| 
modalità_ripristino
 a| 
stringa

Le stringhe supportate da 3 sono _Operational_, _nonoperational_ e _ReadOnly_.
 a| 
Vero



 a| 
annulla_directory_file
 a| 
stringa
 a| 
Vero



 a| 
restore_type
 a| 
stringa
 a| 
Vero

|===


=== Risposta

Se l'API viene eseguita correttamente, viene visualizzato il codice di risposta 202.

Esempio:

[listing]
----
{
  "job": {
    "_links": {
      "self": {
        "href": "/api/resourcelink"
      }
    },
    "uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
  }
}
----