---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery' 
summary: Scopri le novità di BlueXP backup e recovery. 
---
= Novità del backup e ripristino BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità di BlueXP backup e recovery.



== 22 luglio 2024



=== Ripristina volumi inferiori a 1 GB

Con questa versione, è ora possibile ripristinare i volumi creati in ONTAP che sono inferiori a 1 GB. La dimensione minima del volume che è possibile creare utilizzando ONTAP è di 20 MB.



=== Suggerimenti su come ridurre i costi di DataLock

La funzione DataLock protegge i file di backup da modifiche o eliminazioni per un periodo di tempo specificato. Ciò è utile per proteggere i file dagli attacchi ransomware.

Per informazioni dettagliate su DataLock e suggerimenti su come ridurre i costi associati, fare riferimento a link:concept-cloud-backup-policies.html["Impostazioni dei criteri di backup su oggetti"].



=== AWS IAM Roles Anywhere Integration

Il servizio Amazon Web Services (AWS) Identity and Access Management (IAM) Roles Anywhere consente di utilizzare ruoli e credenziali a breve termine IAM per i carichi di lavoro _esterni_ di AWS per accedere in modo sicuro alle API AWS, nello stesso modo in cui si utilizzano i ruoli IAM per i carichi di lavoro _su_ AWS. Quando utilizzi l'infrastruttura a chiave privata IAM Roles Anywhere e i token AWS, non hai bisogno di chiavi di accesso e chiavi segrete AWS a lungo termine. Ciò consente di ruotare le credenziali più frequentemente, migliorando la sicurezza.

Con questa release, il supporto per il servizio AWS IAM Roles Anywhere è un'anteprima tecnologica.

Ciò vale per il backup link:task-backup-to-s3.html["Backup di Cloud Volumes ONTAP su AWS"] e link:task-backup-onprem-to-aws.html["Backup dei dati ONTAP on-premise su AWS"].

Fare riferimento alla https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Blog sulla release di luglio 2024 per backup e recovery di BlueXP"].



=== Ripristino della cartella o della directory FlexGroup ora disponibile

In precedenza era possibile ripristinare i volumi di FlexVol, ma non era possibile ripristinare le cartelle o le directory di FlexGroup. Con ONTAP 9.15.1 P2, è possibile ripristinare le cartelle di FlexGroup utilizzando l'opzione Sfoglia e ripristina.

Con questa versione, il supporto per il ripristino delle cartelle di FlexGroup è un'anteprima tecnologica.

Per ulteriori informazioni, fare riferimento alla link:task-restore-backups-ontap.html#restore-folders-and-files-using-browse-restore["Ripristinare cartelle e file utilizzando Sfoglia  Ripristina"].

Per informazioni dettagliate sull'attivazione manuale, fare riferimento alla https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Blog sulla release di luglio 2024 per backup e recovery di BlueXP"].



== 17 maggio 2024



=== Limitazioni nell'uso di RHEL 8 e RHEL 9 per il connettore in loco

Il connettore BlueXP versione 3.9.40 supporta alcune versioni di Red Hat Enterprise Linux versioni 8 e 9 per l'installazione manuale del software del connettore su host RHEL 8 o 9, indipendentemente dalla posizione e dai sistemi operativi menzionati in https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["requisiti dell'host"^]. Queste nuove versioni RHEL richiedono il motore Podman anziché Docker. Al momento, il backup e il recovery di BlueXP ha due limitazioni quando si utilizza il motore di Podman.

Vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html["Limitazioni di backup e ripristino"] per ulteriori informazioni.

Le seguenti procedure includono le nuove istruzioni di Podman:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-restart-backup.html["Riavviare il backup e il ripristino di BlueXP"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["Ripristinare i dati di backup e ripristino BlueXP in un sito buio"]




== 30 aprile 2024



=== Capacità di abilitare o disabilitare scansioni pianificate di ransomware

In precedenza potevi abilitare o disabilitare le scansioni ransomware, ma non potevi farlo per le scansioni pianificate.

Con questa release, puoi ora abilitare o disabilitare le scansioni ransomware pianificate sull'ultima copia Snapshot utilizzando l'opzione nella pagina Advanced Settings. Se si attiva, le scansioni vengono eseguite settimanalmente per impostazione predefinita. È possibile modificare la pianificazione in giorni o settimane o disattivarla, risparmiando sui costi.

Fare riferimento alle seguenti informazioni per i dettagli:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Gestire le impostazioni di backup"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Gestire le policy per ONTAP Volumes"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["Impostazioni dei criteri di backup su oggetti"]




== 04 aprile 2024



=== Capacità di abilitare o disabilitare le scansioni ransomware

In precedenza, quando hai abilitato il rilevamento di ransomware in una policy di backup, si sono verificate automaticamente le scansioni al momento della creazione del primo backup e al ripristino di un backup. In precedenza, il servizio ha eseguito la scansione di tutte le copie Snapshot e non è stato possibile disattivare le scansioni.

Con questa release, puoi ora abilitare o disabilitare le scansioni ransomware sull'ultima copia Snapshot, utilizzando l'opzione nella pagina Impostazioni avanzate. Se si attiva, le scansioni vengono eseguite settimanalmente per impostazione predefinita.

Fare riferimento alle seguenti informazioni per i dettagli:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Gestire le impostazioni di backup"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Gestire le policy per ONTAP Volumes"]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["Impostazioni dei criteri di backup su oggetti"]




== 12 marzo 2024



=== Possibilità di eseguire "ripristini rapidi" dai backup cloud ai volumi ONTAP on-premise

Ora puoi eseguire un _ripristino rapido_ di un volume dal cloud storage a un volume di destinazione ONTAP on-premise. In precedenza era possibile eseguire un ripristino rapido solo su un sistema Cloud Volumes ONTAP. Il ripristino rapido è ideale per le situazioni di disaster recovery in cui è necessario fornire accesso a un volume il prima possibile. Un ripristino rapido è molto più veloce di un ripristino completo di volumi e ripristina i metadati da una snapshot cloud a un volume di destinazione ONTAP. L'origine potrebbe provenire da AWS S3, BLOB di Azure, Google Cloud Services o NetApp StorageGRID.

Il sistema di destinazione ONTAP on-premise deve eseguire ONTAP versione 9.14.1 o successiva.

È possibile eseguire questa operazione utilizzando il processo di ricerca e ripristino, non il processo di ricerca e ripristino.

Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Ripristinare i dati ONTAP dai file di backup"].



=== Possibilità di ripristinare file e cartelle da copie Snapshot e di replica

In precedenza, potevi ripristinare file e cartelle solo dalle copie di backup in AWS, Azure e Google Cloud Services. Ora, è possibile ripristinare file e cartelle da copie Snapshot locali e da copie di replica.

È possibile eseguire questa funzione utilizzando il processo di ricerca e ripristino, non utilizzando il processo di ricerca e ripristino.



== 01 febbraio 2024



=== Miglioramenti al backup e recovery di BlueXP per Virtual Machine

* Supporta il ripristino di macchine virtuali in una posizione alternativa
* Supporto per la mancata protezione dei datastore




== 15 dicembre 2023



=== Report disponibili per le copie Snapshot locali e di replica

In precedenza, era possibile generare report solo sulle copie di backup. Adesso puoi creare report sulle copie Snapshot locali e sulle copie Snapshot di replica.

Con questi rapporti, è possibile effettuare le seguenti operazioni:

* Assicurati che i dati critici siano protetti in base alla tua politica organizzativa.
* Accertarsi che i backup siano stati eseguiti correttamente per un gruppo di volumi.
* Offri una prova della protezione sui dati di produzione.


Fare riferimento a. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["Report sulla copertura per la data Protection"].



=== Tagging personalizzato disponibile sui volumi per l'ordinamento e il filtraggio

Ora puoi aggiungere tag personalizzati ai volumi a partire da ONTAP 9.13.1 in modo da raggruppare i volumi all'interno e tra gli ambienti di lavoro. In questo modo, puoi ordinare i volumi nelle pagine dell'interfaccia utente di backup e recovery di BlueXP e filtrarli nei report.



=== Backup del catalogo conservati per 30 giorni

In precedenza, Catalog.zip backup venivano conservati per 7 giorni. Ora, sono conservati per 30 giorni.

Fare riferimento a. https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["Ripristina i dati di backup e recovery di BlueXP nei siti oscuri"].



== 23 ottobre 2023



=== creazione del criterio di backup 3-2-1 durante l'attivazione del backup

In precedenza, era necessario creare criteri personalizzati prima di avviare una snapshot, una replica o un backup. Ora puoi creare una policy durante il processo di attivazione del backup utilizzando l'interfaccia utente di backup e recovery di BlueXP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Ulteriori informazioni sulle politiche"].



=== Supporto del ripristino rapido on-demand dei volumi ONTAP

Il backup e recovery di BlueXP ora permette di eseguire un "ripristino rapido" di un volume dal cloud storage a un sistema Cloud Volumes ONTAP. Il ripristino rapido è ideale per le situazioni di disaster recovery in cui è necessario fornire accesso a un volume il prima possibile. Un ripristino rapido ripristina i metadati dal file di backup a un volume invece di ripristinare l'intero file di backup.

Il sistema di destinazione Cloud Volumes ONTAP deve eseguire ONTAP versione 9.13.0 o successiva. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Ulteriori informazioni sul ripristino dei dati"].

Inoltre, il monitoraggio dei processi di backup e ripristino di BlueXP mostra informazioni sullo stato di avanzamento dei processi di ripristino rapido.



=== Supporto per i processi pianificati in Job Monitor

Il monitoraggio del processo di backup e recovery di BlueXP, in precedenza, ha monitorato processi di backup e ripristino pianificati da volume a archivio oggetti, ma non processi di snapshot, replica, backup e ripristino locali pianificati tramite l'interfaccia utente o l'API.

Il monitoraggio dei processi di backup e ripristino di BlueXP include ora i processi pianificati per Snapshot locali, repliche e backup sullo storage a oggetti.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Ulteriori informazioni su Job Monitor aggiornato"].



== 13 ottobre 2023



=== Miglioramenti al backup e ripristino BlueXP per le applicazioni (nativo del cloud)

* Database Microsoft SQL Server
+
** Supporta backup, ripristino e recovery di database Microsoft SQL Server che risiedono in Amazon FSX per NetApp ONTAP
** Tutte le operazioni sono supportate solo tramite API REST.


* Sistemi SAP HANA
+
** Durante l'aggiornamento del sistema, il montaggio e la disinstallazione automatici dei volumi vengono eseguiti utilizzando workflow e non script
** Supporta aggiunta, rimozione, modifica, eliminazione, manutenzione, e l'aggiornamento dell'host plug-in utilizzando l'interfaccia utente






=== Miglioramenti al backup e ripristino BlueXP per le applicazioni (ibrido)

* Supporto del blocco dei dati e della protezione da ransomware
* Supporta lo spostamento dei backup da StorageGRID a Tier di archiviazione
* Supporta il backup dei dati delle applicazioni MongoDB, MySQL e PostgreSQL dai sistemi ONTAP on-premise ad Amazon Web Services, Microsoft Azure, Google Cloud Platform e StorageGRID. È possibile ripristinare i dati quando necessario.




=== Miglioramenti al backup e recovery di BlueXP per Virtual Machine

* Supporto per il modello di distribuzione proxy del connettore




== 11 settembre 2023



=== Nuova gestione delle policy per i dati ONTAP

Questa versione include la possibilità, all'interno dell'interfaccia utente, di creare policy Snapshot personalizzate, policy di replica e policy per i backup sullo storage a oggetti per i dati ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-create-policies-ontap.html["Ulteriori informazioni sulle politiche"].



=== Supporto del ripristino di file e cartelle dai volumi nello storage a oggetti ONTAP S3

In precedenza, non era possibile ripristinare file e cartelle utilizzando la funzione "Sfoglia e ripristina" quando veniva eseguito il backup dei volumi nello storage a oggetti ONTAP S3. Questa versione elimina tale restrizione.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Ulteriori informazioni sul ripristino dei dati"].



=== Possibilità di archiviare immediatamente i dati di backup invece della prima scrittura su storage standard

Ora puoi inviare immediatamente i file di backup allo storage di archiviazione invece di scrivere i dati su un cloud storage standard. Ciò risulta particolarmente utile per gli utenti che raramente hanno bisogno di accedere ai dati da backup del cloud o per gli utenti che stanno sostituendo un ambiente di backup su nastro.



=== Supporto aggiuntivo per il backup e il ripristino di volumi SnapLock

Il backup e il recovery ora possono eseguire il backup di volumi FlexVol e FlexGroup configurati usando la modalità di protezione SnapLock Enterprise. Per supportare questo tipo di supporto, i cluster devono eseguire ONTAP 9,14 o versione successiva. Il backup dei volumi FlexVol utilizzando la modalità SnapLock Enterprise è supportato a partire dalla versione ONTAP 9.11.1. Le release precedenti di ONTAP non supportano il backup di volumi di protezione SnapLock.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Scopri di più sulla protezione dei dati di ONTAP"].



== 1 agosto 2023

[IMPORTANT]
====
* A causa di un importante miglioramento della sicurezza, il connettore ora richiede l'accesso a Internet outbound a un endpoint aggiuntivo per gestire le risorse di backup e ripristino all'interno dell'ambiente cloud pubblico. Se questo endpoint non è stato aggiunto all'elenco "consentito" del firewall, nell'interfaccia utente viene visualizzato un errore relativo a "Servizio non disponibile" o "Impossibile determinare lo stato del servizio":
+
\https://netapp-cloud-account.auth0.com

* Quando utilizzi il pacchetto "CVO Professional" per integrare backup e recovery di Cloud Volumes ONTAP e BlueXP, è necessaria un'iscrizione PAYGO per backup e recovery. Questo non era necessario in passato. Non verranno addebitati costi per l'abbonamento di backup e recovery ai sistemi Cloud Volumes ONTAP idonei, tuttavia tali costi sono necessari durante la configurazione del backup su nuovi volumi.


====


=== È stato aggiunto il supporto per il backup dei volumi nei bucket su sistemi ONTAP S3-configurati

Ora puoi utilizzare un sistema ONTAP che è stato configurato per Simple Storage Service (S3) per eseguire il backup dei volumi nello storage a oggetti. Questo è supportato sia per i sistemi ONTAP on-premise che per i sistemi Cloud Volumes ONTAP. Questa configurazione è supportata in implementazioni cloud e in sedi interne senza accesso a Internet (distribuzione in modalità "privata").

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-ontap-s3.html["Scopri di più"].



=== Ora è possibile includere le istantanee esistenti da un volume protetto nei file di backup

In passato, era possibile includere copie Snapshot esistenti dai volumi in lettura e scrittura del file di backup iniziale nello storage a oggetti (invece di iniziare con la copia Snapshot più recente). Le copie Snapshot esistenti da volumi di sola lettura (volumi di data Protection) non sono state incluse nel file di backup. Ora puoi scegliere di includere copie Snapshot meno recenti nel file di backup per i volumi "DP".

La procedura guidata di backup visualizza un prompt alla fine della procedura di backup in cui è possibile selezionare queste "istantanee esistenti".



=== Il backup e recovery di BlueXP non supporta più il backup automatico dei volumi aggiunti in futuro

In precedenza era possibile selezionare una casella della procedura guidata di backup per applicare il criterio di backup selezionato a tutti i volumi futuri aggiunti al cluster. Questa funzione è stata rimossa in base al feedback dell'utente e alla mancanza di utilizzo di questa funzione. Sarà necessario abilitare manualmente i backup per tutti i nuovi volumi aggiunti al cluster.



=== La pagina monitoraggio processi è stata aggiornata con nuove funzioni

La pagina Job Monitoring fornisce ora ulteriori informazioni relative alla strategia di backup 3-2-1. Il servizio fornisce inoltre notifiche di avviso aggiuntive relative alla strategia di backup.

Il filtro del tipo "ciclo di vita di backup" è stato rinominato "conservazione". Utilizzare questo filtro per tenere traccia del ciclo di vita del backup e per identificare la scadenza di tutte le copie di backup. Il tipo di lavoro "conservazione" acquisisce tutti i processi di eliminazione Snapshot avviati su un volume protetto dal backup e recovery di BlueXP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Ulteriori informazioni su Job Monitor aggiornato"].



== 6 luglio 2023



=== Il backup e ripristino di BlueXP include ora la possibilità di pianificare e creare copie Snapshot e volumi replicati

Il backup e ripristino BlueXP consente ora di implementare una strategia 3-2-1 in cui è possibile avere 3 copie dei dati di origine su 2 sistemi storage diversi e 1 copia nel cloud. Dopo l'attivazione, si avrà a disposizione:

* Copia Snapshot del volume sul sistema di origine
* Volume replicato su un sistema storage diverso
* Backup del volume nello storage a oggetti


https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html["Scopri di più sulle nuove funzionalità di backup e ripristino a spettro completo"].

Questa nuova funzionalità si applica anche alle operazioni di recovery. È possibile eseguire operazioni di ripristino da una copia Snapshot, da un volume replicato o da un file di backup nel cloud. In questo modo è possibile scegliere il file di backup che soddisfa i requisiti di ripristino, inclusi costi e velocità di ripristino.

Si noti che questa nuova funzionalità e l'interfaccia utente sono supportate solo per i cluster che eseguono ONTAP 9.8 o versione successiva. Se il cluster dispone di una versione precedente del software, è possibile continuare a utilizzare la versione precedente di backup e ripristino di BlueXP. Tuttavia, si consiglia di eseguire l'aggiornamento a una versione supportata di ONTAP per ottenere le funzionalità e le funzionalità più recenti. Per continuare a utilizzare la versione precedente del software, attenersi alla seguente procedura:

. Dalla scheda *Volumes* (volumi), selezionare *Backup Settings* (Impostazioni di backup).
. Dalla pagina _Backup Settings_, fare clic sul pulsante di opzione *Visualizza la versione precedente di backup e ripristino di BlueXP*.
+
Quindi, puoi gestire i cluster meno recenti utilizzando la versione precedente del software.





=== Possibilità di creare un container di storage per il backup sullo storage a oggetti

Per impostazione predefinita, quando si creano file di backup nello storage a oggetti, il servizio di backup e ripristino crea i bucket nello storage a oggetti. È possibile creare autonomamente i bucket se si desidera utilizzare un determinato nome o assegnare proprietà speciali. Se si desidera creare un bucket personalizzato, è necessario crearlo prima di avviare l'attivazione guidata. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["Scopri come creare i bucket di storage a oggetti"].

Questa funzionalità non è attualmente supportata quando si creano file di backup su sistemi StorageGRID.



== 04 luglio 2023



=== Miglioramenti al backup e ripristino BlueXP per le applicazioni (nativo del cloud)

* Sistemi SAP HANA
+
** Supporta il ripristino di connessione e copia di volumi non dati e volumi non dati globali con protezione secondaria Azure NetApp Files


* Database Oracle
+
** Supporta il ripristino dei database Oracle su Azure NetApp Files in una posizione alternativa
** Supporta la catalogazione di Oracle Recovery Manager (RMAN) dei backup dei database Oracle su Azure NetApp Files
** Consente di impostare l'host del database in modalità di manutenzione per eseguire le attività di manutenzione






=== Miglioramenti al backup e ripristino BlueXP per le applicazioni (ibrido)

* Supporta il ripristino in una posizione alternativa
* Consente di montare backup di database Oracle
* Supporta lo spostamento dei backup da GCP a Tier di archiviazione




=== Miglioramenti al backup e ripristino BlueXP per macchine virtuali (ibrido)

* Supporta la protezione di datastore di tipo NFS e VMFS
* Consente di annullare la registrazione del plug-in SnapCenter per l'host VMware vSphere
* Supporta il refresh e il rilevamento di datastore e backup più recenti




== 5 giugno 2023



=== È possibile eseguire il backup e la protezione dei volumi FlexGroup utilizzando DataLock e la protezione ransomware

I criteri di backup per i volumi FlexGroup possono ora utilizzare la protezione DataLock e ransomware quando il cluster esegue ONTAP 9.13.1 o superiore.



=== Nuove funzionalità di reporting

È ora disponibile una scheda Report in cui è possibile generare un report di Backup Inventory, che include tutti i backup per un account specifico, un ambiente di lavoro o un inventario SVM. È inoltre possibile creare un report Data Protection Job Activity, che fornisce informazioni sulle operazioni di Snapshot, backup, clonazione e ripristino che possono essere utili per il monitoraggio dei contratti di servizio. Fare riferimento a. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-report-inventory.html["Report sulla copertura per la data Protection"].



=== Miglioramenti di Job Monitor

È ora possibile rivedere il _ciclo di vita del backup_ come tipo di lavoro nella pagina Job Monitor, per tenere traccia dell'intero ciclo di vita del backup. È inoltre possibile visualizzare i dettagli di tutte le operazioni nella timeline di BlueXP. Fare riferimento a. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Monitorare lo stato dei processi di backup e ripristino"].



=== Avviso di notifica aggiuntivo per etichette di policy non corrispondenti

È stato aggiunto un nuovo avviso di backup: "I file di backup non sono stati creati perché le etichette dei criteri Snapshot non corrispondono". Se la _label_ definita in un criterio di backup non ha un'etichetta _corrispondente_ nel criterio Snapshot, non verrà creato alcun file di backup. Per aggiungere l'etichetta mancante al criterio Snapshot del volume, è necessario utilizzare Gestione di sistema o l'interfaccia utente di ONTAP.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["Esaminare tutti gli avvisi che il backup e ripristino BlueXP può inviare"].



=== Backup automatico dei file critici di backup e ripristino BlueXP in siti bui

Quando si utilizza il backup e ripristino BlueXP in un sito senza accesso a Internet, noto come implementazione in "modalità privata", le informazioni di backup e ripristino di BlueXP vengono memorizzate solo sul sistema di connessione locale. Questa nuova funzionalità esegue automaticamente il backup dei dati critici di backup e ripristino di BlueXP su un bucket del sistema StorageGRID connesso, in modo da poter ripristinare questi dati su un nuovo connettore, se necessario. https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-backup-cbs-db-in-dark-site.html["Scopri di più"]



== 8 maggio 2023



=== Le operazioni di ripristino a livello di cartella sono ora supportate dallo storage di archiviazione e dai backup bloccati

Se un file di backup è stato configurato con la protezione DataLock & ransomware o se il file di backup risiede nello storage di archiviazione, ora le operazioni di ripristino a livello di cartella sono supportate se il cluster esegue ONTAP 9.13.1 o superiore.



=== Le chiavi gestite dal cliente per più aree e progetti sono supportate quando si esegue il backup dei volumi su Google Cloud

Ora puoi scegliere un bucket che si trova in un progetto diverso rispetto al progetto delle chiavi di crittografia gestite dal cliente (CMEK). https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["Scopri di più sulla configurazione delle tue chiavi di crittografia gestite dal cliente"].



=== Le regioni AWS China sono ora supportate per i file di backup

Le regioni AWS China Pechino (cn-North-1) e Ningxia (cn-Nordovest-1) sono ora supportate come destinazioni per i file di backup se il cluster esegue ONTAP 9.12.1 o superiore.

Si noti che i criteri IAM assegnati al connettore BlueXP devono modificare il nome risorsa AWS "arn" in tutte le sezioni _Resource_ da "aws" a "aws-cn", ad esempio "arn:aws-cn:s3:::netapp-backup-*". Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Eseguire il backup dei dati Cloud Volumes ONTAP su Amazon S3"] e. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-aws.html["Eseguire il backup dei dati ONTAP on-premise su Amazon S3"]



=== Miglioramenti di Job Monitor

I processi avviati dal sistema, come le operazioni di backup in corso, sono ora disponibili nella scheda *monitoraggio del processo* per i sistemi ONTAP on-premise che eseguono ONTAP 9.13.1 o versione successiva. Le versioni precedenti di ONTAP visualizzano solo i processi avviati dall'utente.



== 14 aprile 2023



=== Miglioramenti al backup e ripristino BlueXP per le applicazioni (nativo del cloud)

* Database SAP HANA
+
** Supporta l'aggiornamento del sistema basato su script
** Supporta Single-file-Snapshot-Restore se è configurato il backup Azure NetApp Files
** Supporta l'upgrade del plug-in


* Database Oracle
+
** Miglioramenti all'implementazione del plug-in attraverso la semplificazione della configurazione utente sudo non root
** Supporta l'upgrade del plug-in
** Supporta il rilevamento automatico e la protezione basata su policy dei database Oracle su Azure NetApp Files
** Supporta il ripristino del database Oracle nella posizione originale con ripristino granulare






=== Miglioramenti al backup e ripristino BlueXP per le applicazioni (ibrido)

* Il backup e ripristino BlueXP per le applicazioni (ibrido) è basato sul piano di controllo SaaS
* Sono state modificate le API REST ibride per allinearle alle API native del cloud.
* Supporta la notifica via email




== 4 aprile 2023



=== Possibilità di eseguire il backup dei dati nel cloud dai sistemi Cloud Volumes ONTAP in modalità "limitata"

Ora è possibile eseguire il backup dei dati dai sistemi Cloud Volumes ONTAP installati nelle aree commerciali AWS, Azure e GCP in "modalità limitata". Ciò richiede l'installazione del connettore nella regione commerciale "limitata". https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Scopri di più sulle modalità di implementazione di BlueXP"^]. Vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Backup dei dati Cloud Volumes ONTAP su Amazon S3"] e. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Backup dei dati Cloud Volumes ONTAP in Azure Blob"].



=== Possibilità di eseguire il backup dei volumi ONTAP on-premise su ONTAP S3 utilizzando l'API

Le nuove funzionalità delle API consentono di eseguire il backup delle snapshot dei volumi in ONTAP S3 utilizzando il backup e ripristino BlueXP. Questa funzionalità è attualmente disponibile solo per i sistemi ONTAP on-premise. Per istruzioni dettagliate, consulta il blog https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-Feature-Blog-April-23-Updates/ba-p/443075#toc-hId--846533830["Integrazione con ONTAP S3 come destinazione"^].



=== Possibilità di modificare l'aspetto della ridondanza di zona dell'account di storage Azure da LRS a ZRS

Quando si creano backup dai sistemi Cloud Volumes ONTAP allo storage Azure, per impostazione predefinita, il backup e ripristino BlueXP esegue il provisioning del container Blob con ridondanza locale (LRS) per l'ottimizzazione dei costi. È possibile modificare questa impostazione in ZRS (zone Redundancy) se si desidera che i dati vengano replicati tra zone diverse. Consultare le istruzioni Microsoft per https://learn.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal["modifica della modalità di replica dell'account storage"^].



=== Miglioramenti di Job Monitor

* Sia le operazioni di backup e ripristino avviate dall'utente dall'interfaccia utente e dall'API di backup e ripristino di BlueXP, sia i processi avviati dal sistema, come le operazioni di backup in corso, sono ora disponibili nella scheda *monitoraggio del processo* per i sistemi Cloud Volumes ONTAP che eseguono ONTAP 9.13.0 o versione successiva. Le versioni precedenti di ONTAP visualizzano solo i processi avviati dall'utente.
* Oltre a poter scaricare un file CSV per la creazione di report su tutti i lavori, ora è possibile scaricare un file JSON per un singolo lavoro e visualizzarne i dettagli. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["Scopri di più"].
* Sono stati aggiunti due nuovi avvisi relativi al processo di backup: "Errore del processo pianificato" e "il processo di ripristino viene completato ma con avvisi". https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#review-backup-and-restore-alerts-in-the-bluexp-notification-center["Esaminare tutti gli avvisi che il backup e ripristino BlueXP può inviare"].




== 9 marzo 2023



=== Le operazioni di ripristino a livello di cartella ora includono tutte le sottocartelle e i file

In passato, quando si ripristinava una cartella, venivano ripristinati solo i file di tale cartella, senza alcuna sottocartella o file di sottocartelle. Ora, se si utilizza ONTAP 9.13.0 o versione successiva, vengono ripristinate tutte le sottocartelle e i file nella cartella selezionata. Ciò consente di risparmiare molto tempo e denaro nei casi in cui si dispone di più cartelle nidificate in una cartella di primo livello.



=== Capacità di eseguire il backup dei dati dai sistemi Cloud Volumes ONTAP nei siti con una connettività in uscita limitata

Ora puoi eseguire il backup dei dati dai sistemi Cloud Volumes ONTAP installati nelle aree commerciali di AWS e Azure su Amazon S3 o Azure Blob. Questo richiede che il connettore venga installato in "modalità limitata" su un host Linux nella regione commerciale e che venga installato anche il sistema Cloud Volumes ONTAP. Vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-s3.html["Backup dei dati Cloud Volumes ONTAP su Amazon S3"] e. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-to-azure.html["Backup dei dati Cloud Volumes ONTAP in Azure Blob"].



=== Miglioramenti multipli di Job Monitor

* La pagina monitoraggio processi ha aggiunto un filtro avanzato che consente di cercare i processi di backup e ripristino in base a tempo, carico di lavoro (volumi, applicazioni o macchine virtuali), tipo di lavoro, stato, ambiente di lavoro e VM di storage. È anche possibile inserire testo libero per cercare qualsiasi risorsa, ad esempio "application_3".  https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#searching-and-filtering-the-list-of-jobs["Scopri come utilizzare i filtri avanzati"].
* Sia le operazioni di backup e ripristino avviate dall'utente dall'interfaccia utente e dall'API di backup e ripristino di BlueXP, sia i processi avviati dal sistema, come le operazioni di backup in corso, sono ora disponibili nella scheda *monitoraggio del processo* per i sistemi Cloud Volumes ONTAP che eseguono ONTAP 9.13.0 o versione successiva. Le versioni precedenti dei sistemi Cloud Volumes ONTAP e dei sistemi ONTAP on-premise visualizzano solo i processi avviati dall'utente.




== 6 febbraio 2023



=== Possibilità di spostare i file di backup meno recenti nello storage di archiviazione Azure dai sistemi StorageGRID

Ora puoi eseguire il tiering dei file di backup più vecchi dai sistemi StorageGRID allo storage di archiviazione in Azure. Ciò consente di liberare spazio sui sistemi StorageGRID e di risparmiare denaro utilizzando una classe di storage economica per i file di backup meno recenti.

Questa funzionalità è disponibile se il cluster on-premise utilizza ONTAP 9.12.1 o versione successiva e il sistema StorageGRID utilizza 11.4 o versione successiva. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["Scopri di più qui"^].



=== La protezione DataLock e ransomware può essere configurata per i file di backup in Azure Blob

DataLock e ransomware Protection sono ora supportati per i file di backup memorizzati in Azure Blob. Se il sistema Cloud Volumes ONTAP o on-premise ONTAP utilizza ONTAP 9.12.1 o versione successiva, è ora possibile bloccare i file di backup ed eseguirne la scansione per rilevare eventuali ransomware. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Scopri di più su come proteggere i backup utilizzando DataLock e la protezione ransomware"^].



=== Miglioramenti del volume FlexGroup di backup e ripristino

* È ora possibile scegliere più aggregati durante il ripristino di un volume FlexGroup. Nell'ultima release è possibile selezionare solo un singolo aggregato.
* Il ripristino del volume FlexGroup è ora supportato sui sistemi Cloud Volumes ONTAP. Nell'ultima release è possibile eseguire il ripristino solo su sistemi ONTAP on-premise.




=== I sistemi Cloud Volumes ONTAP possono spostare i backup meno recenti nello storage di Google Archives

I file di backup vengono creati inizialmente nella classe di storage Google Standard. Ora è possibile utilizzare il backup e il ripristino BlueXP per eseguire il tiering dei backup più vecchi sullo storage Google Archive per un'ulteriore ottimizzazione dei costi. L'ultima release supportava questa funzionalità solo con cluster ONTAP on-premise, ora sono supportati i sistemi Cloud Volumes ONTAP implementati in Google Cloud.



=== Le operazioni di ripristino del volume consentono ora di selezionare la SVM in cui si desidera ripristinare i dati del volume

Ora ripristini i dati dei volumi su diverse macchine virtuali dello storage nei cluster ONTAP. In passato non era possibile scegliere la VM di storage.



=== Supporto migliorato per i volumi nelle configurazioni MetroCluster

Quando si utilizza ONTAP 9.12.1 GA o superiore, il backup è ora supportato quando si è connessi al sistema primario in una configurazione MetroCluster. L'intera configurazione di backup viene trasferita al sistema secondario in modo che i backup nel cloud continuino automaticamente dopo lo switchover.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#backup-limitations["Per ulteriori informazioni, vedere limitazioni del backup"].



== 9 gennaio 2023



=== Possibilità di spostare i file di backup meno recenti nello storage di archiviazione AWS S3 dai sistemi StorageGRID

Ora è possibile eseguire il tiering dei file di backup più vecchi dai sistemi StorageGRID allo storage di archiviazione in AWS S3. Ciò consente di liberare spazio sui sistemi StorageGRID e di risparmiare denaro utilizzando una classe di storage economica per i file di backup meno recenti. È possibile scegliere di eseguire il Tier dei backup nello storage AWS S3 Glacier o S3 Glacier Deep Archive.

Questa funzionalità è disponibile se il cluster on-premise utilizza ONTAP 9.12.1 o versione successiva e il sistema StorageGRID utilizza 11.3 o versione successiva. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html#preparing-to-archive-older-backup-files-to-public-cloud-storage["Scopri di più qui"].



=== Possibilità di selezionare le chiavi gestite dal cliente per la crittografia dei dati su Google Cloud

Quando si esegue il backup dei dati dai sistemi ONTAP su Google Cloud Storage, è ora possibile selezionare le proprie chiavi gestite dal cliente per la crittografia dei dati nella procedura guidata di attivazione invece di utilizzare le chiavi di crittografia predefinite gestite da Google. Devi solo configurare le chiavi di crittografia gestite dal cliente in Google, quindi inserire i dettagli durante l'attivazione del backup e ripristino BlueXP.



=== Il ruolo "Storage Admin" non è più necessario per l'account del servizio per creare backup in Google Cloud Storage

Nelle versioni precedenti, il ruolo "Storage Admin" era richiesto per l'account del servizio che consente il backup e il ripristino BlueXP per accedere ai bucket di storage Google Cloud. Ora è possibile creare un ruolo personalizzato con un set ridotto di autorizzazioni da assegnare all'account del servizio. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-to-gcp.html#preparing-google-cloud-storage-for-backups["Scopri come preparare il tuo Google Cloud Storage per i backup"].



=== È stato aggiunto il supporto per il ripristino dei dati utilizzando Search & Restore nei siti senza accesso a Internet

Se si esegue il backup dei dati da un cluster ONTAP on-premise a StorageGRID in un sito senza accesso a Internet, noto anche come sito oscuro o offline, è ora possibile utilizzare l'opzione Cerca e ripristina per ripristinare i dati, se necessario. Questa funzionalità richiede l'implementazione di BlueXP Connector (versione 3.9.25 o superiore) nel sito offline.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restoring-ontap-data-using-search-restore["Scopri come ripristinare i dati ONTAP utilizzando Cerca  Ripristina"].
https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-private-mode.html["Scopri come installare il connettore nel tuo sito offline"].



=== Possibilità di scaricare la pagina dei risultati di Job Monitoring come report .csv

Dopo aver filtrato la pagina Job Monitoring per visualizzare i lavori e le azioni a cui si è interessati, è possibile generare e scaricare un file .csv di tali dati. Quindi, è possibile analizzare le informazioni o inviare il report ad altre persone della propria organizzazione. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#download-job-monitoring-results-as-a-report["Scopri come generare un report di monitoraggio dei processi"].



== 19 dicembre 2022



=== Miglioramenti al Cloud Backup per le applicazioni

* Database SAP HANA
+
** Supporta il backup e il ripristino basati su policy dei database SAP HANA residenti su Azure NetApp Files
** Supporta policy personalizzate


* Database Oracle
+
** Aggiungere host e implementare il plug-in automaticamente
** Supporta policy personalizzate
** Supporta backup, ripristino e clone basati su policy di database Oracle residenti su Cloud Volumes ONTAP
** Supporta il backup e il ripristino basati su policy dei database Oracle residenti su Amazon FSX per NetApp ONTAP
** Supporta il ripristino dei database Oracle utilizzando il metodo Connect-and-copy
** Supporta Oracle 21c
** Supporta la clonazione del database Oracle nativo nel cloud






=== Miglioramenti al Cloud Backup per macchine virtuali

* Macchine virtuali
+
** Eseguire il backup delle macchine virtuali dallo storage secondario on-premise
** Supporta policy personalizzate
** Supporta Google Cloud Platform (GCP) per il backup di uno o più datastore
** Supporta lo storage cloud a basso costo come Glacier, Deep Glacier e Azure Archive






== 6 dicembre 2022



=== Modifiche richieste all'endpoint di accesso a Internet in uscita del connettore

A causa di una modifica nel Cloud Backup, è necessario modificare i seguenti endpoint del connettore per un'operazione di backup cloud corretta:

[cols="50,50"]
|===
| Vecchio endpoint | Nuovo endpoint 


| https://cloudmanager.cloud.netapp.com | https://api.bluexp.netapp.com 


| https://*.cloudmanager.cloud.netapp.com | https://*.api.bluexp.netapp.com 
|===
Consulta l'elenco completo degli endpoint per il https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-aws.html#outbound-internet-access["AWS"^], https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-google.html#outbound-internet-access["Google Cloud"^], o. https://docs.netapp.com/us-en/bluexp-setup-admin/task-set-up-networking-azure.html#outbound-internet-access["Azure"^] ambiente cloud.



=== Supporto per la selezione della classe di storage Google Archival nell'interfaccia utente

I file di backup vengono creati inizialmente nella classe di storage Google Standard. Ora puoi utilizzare l'interfaccia utente di Cloud Backup per eseguire il tiering dei backup più vecchi sullo storage di Google Archive dopo un certo numero di giorni per un'ulteriore ottimizzazione dei costi.

Questa funzionalità è attualmente supportata per i cluster ONTAP on-premise che utilizzano ONTAP 9.12.1 o versione successiva. Attualmente non è disponibile per i sistemi Cloud Volumes ONTAP.



=== Supporto per FlexGroup Volumes

Cloud Backup ora supporta il backup e il ripristino dei volumi FlexGroup. Quando utilizzi ONTAP 9.12.1 o superiore, puoi eseguire il backup dei volumi FlexGroup su cloud storage pubblico e privato. Se si dispone di ambienti di lavoro che includono volumi FlexVol e FlexGroup, una volta aggiornato il software ONTAP, è possibile eseguire il backup di qualsiasi volume FlexGroup su tali sistemi.

https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html#supported-volumes["Consulta l'elenco completo dei tipi di volume supportati"].



=== Possibilità di ripristinare i dati dai backup su un aggregato specifico nei sistemi Cloud Volumes ONTAP

Nelle versioni precedenti era possibile selezionare l'aggregato solo quando si ripristinano i dati su sistemi ONTAP on-premise. Questa funzionalità ora funziona quando si ripristinano i dati sui sistemi Cloud Volumes ONTAP.



== 2 novembre 2022



=== Possibilità di esportare copie Snapshot meno recenti nei file di backup di riferimento

Se nell'ambiente di lavoro sono presenti copie Snapshot locali per volumi che corrispondono alle etichette della pianificazione di backup (ad esempio, giornaliere, settimanali, ecc.), è possibile esportare tali snapshot cronologici nello storage a oggetti come file di backup. Ciò consente di inizializzare i backup nel cloud spostando le copie snapshot meno recenti nella copia di backup di riferimento.

Questa opzione è disponibile quando si attiva Cloud Backup per gli ambienti di lavoro. Questa impostazione può essere modificata anche in un secondo momento in https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Pagina Advanced Settings (Impostazioni avanzate)"].



=== Cloud Backup può ora essere utilizzato per l'archiviazione di volumi non più necessari sul sistema di origine

Ora è possibile eliminare la relazione di backup per un volume. Questo offre un meccanismo di archiviazione se si desidera interrompere la creazione di nuovi file di backup ed eliminare il volume di origine, conservando tutti i file di backup esistenti. Ciò consente di ripristinare il volume dal file di backup in futuro, se necessario, liberando spazio dal sistema di storage di origine. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backups-ontap.html#deleting-volume-backup-relationships["Scopri come"].



=== È stato aggiunto il supporto per ricevere gli avvisi Cloud Backup tramite e-mail e nel Centro notifiche

Cloud Backup è stato integrato nel servizio di notifica BlueXP. È possibile visualizzare le notifiche di Cloud Backup facendo clic sulla campana di notifica nella barra dei menu di BlueXP. È inoltre possibile configurare BlueXP per inviare notifiche via email come avvisi, in modo da essere informati di importanti attività del sistema anche quando non si è connessi al sistema. L'e-mail può essere inviata a tutti i destinatari che devono essere a conoscenza dell'attività di backup e ripristino. https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html#use-the-job-monitor-to-view-backup-and-restore-job-status["Scopri come"].



=== La nuova pagina Advanced Settings (Impostazioni avanzate) consente di modificare le impostazioni di backup a livello di cluster

Questa nuova pagina consente di modificare molte impostazioni di backup a livello di cluster impostate durante l'attivazione del backup cloud per ciascun sistema ONTAP. È inoltre possibile modificare alcune impostazioni applicate come impostazioni di backup predefinite. Il set completo di impostazioni di backup che è possibile modificare comprende:

* Le chiavi di storage che danno al sistema ONTAP l'autorizzazione ad accedere allo storage a oggetti
* Larghezza di banda della rete allocata per caricare i backup nello storage a oggetti
* L'impostazione (e il criterio) di backup automatico per i volumi futuri
* Classe di storage di archiviazione (solo AWS)
* Se le copie Snapshot storiche sono incluse nei file di backup di riferimento iniziali
* Se le istantanee "annuali" vengono rimosse dal sistema di origine
* Spazio IP ONTAP connesso allo storage a oggetti (in caso di selezione errata durante l'attivazione)


https://docs.netapp.com/us-en/bluexp-backup-recovery/task-manage-backup-settings-ontap.html["Scopri di più sulla gestione delle impostazioni di backup a livello di cluster"].



=== Ora è possibile ripristinare i file di backup utilizzando Search & Restore quando si utilizza un connettore on-premise

Nella release precedente, è stato aggiunto il supporto per la creazione di file di backup nel cloud pubblico quando il connettore viene distribuito nelle vostre sedi. In questa versione, il supporto è stato continuato per consentire l'utilizzo di Search & Restore per ripristinare i backup da Amazon S3 o Azure Blob quando il connettore viene distribuito nella tua sede. Search & Restore supporta anche il ripristino dei backup dai sistemi StorageGRID ai sistemi ONTAP on-premise.

A questo punto, il connettore deve essere implementato nella piattaforma Google Cloud quando si utilizza Search & Restore per ripristinare i backup da Google Cloud Storage.



=== La pagina Job Monitoring è stata aggiornata

Sono stati apportati i seguenti aggiornamenti a https://docs.netapp.com/us-en/bluexp-backup-recovery/task-monitor-backup-jobs.html["Pagina Job Monitoring"]:

* È disponibile una colonna per "carico di lavoro" che consente di filtrare la pagina per visualizzare i lavori per i seguenti servizi di backup: Volumi, applicazioni e macchine virtuali.
* È possibile aggiungere nuove colonne per "Nome utente" e "tipo di lavoro" se si desidera visualizzare questi dettagli per un processo di backup specifico.
* La pagina Dettagli lavoro visualizza tutti i lavori secondari in esecuzione per completare il lavoro principale.
* La pagina viene aggiornata automaticamente ogni 15 minuti in modo da visualizzare sempre i risultati più recenti dello stato del lavoro. E fare clic sul pulsante *Refresh* (Aggiorna) per aggiornare immediatamente la pagina.




=== Miglioramenti del backup multiaccount AWS

Se si desidera utilizzare un account AWS diverso da quello utilizzato per i volumi di origine per i backup Cloud Volumes ONTAP, è necessario aggiungere le credenziali dell'account AWS di destinazione in BlueXP e aggiungere le autorizzazioni "s3:PutBucketPolicy" e "s3:PutBucketOwnershipControls" al ruolo IAM che fornisce a BlueXP le autorizzazioni. In passato, era necessario configurare molte impostazioni nella console AWS, ma non è più necessario farlo.



== 28 settembre 2022



=== Miglioramenti al Cloud Backup per le applicazioni

* Supporta Google Cloud Platform (GCP) e StorageGRID per il backup di snapshot coerenti con l'applicazione
* Creare policy personalizzate
* Supporta lo storage di archiviazione
* Eseguire il backup delle applicazioni SAP HANA
* Eseguire il backup delle applicazioni Oracle e SQL presenti nell'ambiente VMware
* Eseguire il backup delle applicazioni dallo storage secondario on-premise
* Disattivare i backup
* Annullare la registrazione del server SnapCenter




=== Miglioramenti al Cloud Backup per macchine virtuali

* Supporta StorageGRID per il backup di uno o più datastore
* Creare policy personalizzate




== 19 settembre 2022



=== È possibile configurare la protezione DataLock e ransomware per i file di backup nei sistemi StorageGRID

L'ultima release ha introdotto _DataLock e ransomware Protection_ per i backup memorizzati nei bucket Amazon S3. Questa release estende il supporto ai file di backup memorizzati nei sistemi StorageGRID. Se il cluster utilizza ONTAP 9.11.1 o versione successiva e il sistema StorageGRID esegue la versione 11.6.0.3 o successiva, questa nuova opzione dei criteri di backup è disponibile. https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html#datalock-and-ransomware-protection["Scopri di più su come utilizzare DataLock e la protezione ransomware per proteggere i tuoi backup"^].

Tenere presente che è necessario eseguire un connettore con la versione 3.9.22 o superiore del software. Il connettore deve essere installato in sede e può essere installato in un sito con o senza accesso a Internet.



=== Il ripristino a livello di cartella è ora disponibile dai file di backup

Ora è possibile ripristinare una cartella da un file di backup se si ha bisogno di accedere a tutti i file in tale cartella (directory o condivisione). Il ripristino di una cartella è molto più efficiente del ripristino di un intero volume. Questa funzionalità è disponibile per le operazioni di ripristino utilizzando sia il metodo Browse & Restore che il metodo Search & Restore quando si utilizza ONTAP 9.11.1 o versione successiva. In questo momento è possibile selezionare e ripristinare solo una singola cartella e ripristinare solo i file di tale cartella. Non vengono ripristinate sottocartelle o file di sottocartelle.



=== Il ripristino a livello di file è ora disponibile dai backup spostati nello storage di archiviazione

In passato era possibile ripristinare solo i volumi dai file di backup spostati nello storage di archiviazione (solo AWS e Azure). Ora è possibile ripristinare singoli file da questi file di backup archiviati. Questa funzionalità è disponibile per le operazioni di ripristino utilizzando sia il metodo Browse & Restore che il metodo Search & Restore quando si utilizza ONTAP 9.11.1 o versione successiva.



=== Il ripristino a livello di file consente ora di sovrascrivere il file di origine originale

In passato, un file ripristinato nel volume originale veniva sempre ripristinato come nuovo file con il prefisso "Restore_<file_name>". È ora possibile scegliere di sovrascrivere il file di origine originale quando si ripristina il file nella posizione originale sul volume. Questa funzionalità è disponibile per le operazioni di ripristino utilizzando sia il metodo Browse & Restore che il metodo Search & Restore.



=== Trascinare e rilasciare per abilitare il backup cloud sui sistemi StorageGRID

Se il https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["StorageGRID"^] La destinazione dei backup esiste come ambiente di lavoro su Canvas. È possibile trascinare l'ambiente di lavoro ONTAP on-premise sulla destinazione per avviare l'installazione guidata del backup cloud.
