---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, backup, restore, bluexp, bluexp backup and recovery, protection' 
summary: Scopri le novità di BlueXP backup e recovery. 
---
= Novità nel backup e ripristino di BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le novità di BlueXP backup e recovery.



== 14 luglio 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Dashboard del volume ONTAP migliorato

Ad aprile 2025 abbiamo lanciato un'anteprima di una Dashboard del volume ONTAP migliorata, molto più veloce ed efficiente.

Questa dashboard è stata progettata per supportare i clienti aziendali con un elevato numero di carichi di lavoro. Anche per i clienti con 20.000 volumi, la nuova dashboard si carica in meno di 10 secondi.

Dopo un'anteprima di successo e un feedback positivo da parte dei clienti, ora la stiamo rendendo l'esperienza predefinita per tutti i nostri clienti. Preparatevi per una dashboard incredibilmente veloce.

Per ulteriori informazioni, vedere link:br-use-dashboard.html["Visualizza lo stato di protezione nella Dashboard"].



=== Supporto del carico di lavoro di Microsoft SQL Server come anteprima tecnologica pubblica

Questa versione di BlueXP backup and recovery offre un'interfaccia utente aggiornata che consente di gestire i carichi di lavoro di Microsoft SQL Server utilizzando una strategia di protezione 3-2-1, già nota nel servizio di BlueXP backup and recovery . Con questa nuova versione, è possibile eseguire il backup di questi carichi di lavoro sullo storage primario, replicarli sullo storage secondario ed eseguirne il backup sullo storage di oggetti cloud.

Puoi iscriverti all'anteprima completando questo  https://forms.office.com/pages/responsepage.aspx?id=oBEJS5uSFUeUS8A3RRZbOojtBW63mDRDv3ZK50MaTlJUNjdENllaVTRTVFJGSDQ2MFJIREcxN0EwQi4u&route=shorturl["Anteprima del modulo di registrazione"^] .


NOTE: LA PRESENTE DOCUMENTAZIONE SULLA PROTEZIONE DEI CARICHI DI LAVORO DI MICROSOFT SQL SERVER VIENE FORNITA COME ANTEPRIMA TECNOLOGICA. Con questa offerta di anteprima, NetApp si riserva il diritto di modificare i dettagli dell'offerta, i contenuti e la tempistica prima della disponibilità generale.

Questa versione di BlueXP backup and recovery include i seguenti aggiornamenti:

* *Funzionalità di backup 3-2-1*: questa versione integra le funzionalità SnapCenter , consentendo di gestire e proteggere le risorse SnapCenter con una strategia di protezione dei dati 3-2-1 dall'interfaccia utente BlueXP backup and recovery .
* *Importa da SnapCenter*: puoi importare i dati di backup e i criteri SnapCenter nel BlueXP backup and recovery.
* *Un'interfaccia utente riprogettata* offre un'esperienza più intuitiva per la gestione delle attività di backup e ripristino.
* *Destinazioni di backup*: puoi aggiungere bucket negli ambienti Amazon Web Services (AWS), Microsoft Azure Blob Storage, StorageGRID e ONTAP S3 da utilizzare come destinazioni di backup per i carichi di lavoro di Microsoft SQL Server.
* *Supporto per i carichi di lavoro*: questa versione consente di eseguire il backup, il ripristino, la verifica e la clonazione di database e gruppi di disponibilità di Microsoft SQL Server. (Il supporto per altri carichi di lavoro verrà aggiunto nelle versioni future.)
* *Opzioni di ripristino flessibili*: questa versione consente di ripristinare i database sia nelle posizioni originali che in quelle alternative in caso di danneggiamento o perdita accidentale dei dati.
* *Copie di produzione istantanee*: genera copie di produzione salvaspazio per sviluppo, test o analisi in pochi minuti anziché in ore o giorni.
* Questa versione include la possibilità di creare report dettagliati.


Per informazioni dettagliate sulla protezione dei carichi di lavoro di Microsoft SQL Server, vedere link:br-use-mssql-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro di Microsoft SQL Server"] .



== 09 giugno 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Aggiornamenti del supporto del catalogo indicizzato

A febbraio 2025, abbiamo introdotto la funzionalità di indicizzazione aggiornata (Catalogo indicizzato v2) da utilizzare durante il metodo di ripristino dei dati "Cerca e ripristina". La versione precedente ha migliorato significativamente le prestazioni di indicizzazione dei dati negli ambienti on-premise. Con questa versione, il catalogo di indicizzazione è ora disponibile negli ambienti Amazon Web Services, Microsoft Azure e Google Cloud Platform (GCP).

Se sei un nuovo cliente, il Catalogo Indicizzato v2 è abilitato per impostazione predefinita per tutti i nuovi ambienti. Se sei un cliente esistente, puoi reindicizzare il tuo ambiente per sfruttare il Catalogo Indicizzato v2.

.Come si attiva l'indicizzazione?
Prima di poter utilizzare il metodo Search & Restore per il ripristino dei dati, è necessario attivare l'indicizzazione in ogni ambiente di lavoro di origine da cui si prevede di ripristinare volumi o file. Selezionare l'opzione *Abilita indicizzazione* quando si esegue una ricerca e un ripristino.

Il catalogo indicizzato può quindi tenere traccia di ogni volume e file di backup, rendendo le ricerche rapide ed efficienti.

Per ulteriori informazioni, vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Come ripristinare i dati ONTAP utilizzando Cerca  Ripristina"].



=== Endpoint di collegamento privato di Azure ed endpoint di servizio

In genere, il backup e il ripristino di BlueXP stabiliscono un endpoint privato con il provider cloud per gestire diverse attività di protezione. Questa versione introduce un'impostazione opzionale che consente di abilitare o disabilitare la creazione automatica di un endpoint privato da parte di BlueXP Backup and Recovery. Questa opzione potrebbe essere utile se si desidera un maggiore controllo sul processo di creazione di endpoint privati.

È possibile abilitare o disabilitare questa opzione quando si abilita la protezione o si avvia il processo di ripristino.

Se si disabilita questa impostazione, è necessario creare manualmente l'endpoint privato affinché il backup e il ripristino di BlueXP funzionino correttamente. Senza una connettività adeguata, potrebbe non essere possibile eseguire correttamente le attività di backup e ripristino.



=== Supporto per SnapMirror su Cloud Resync su ONTAP S3

La versione precedente ha introdotto il supporto per SnapMirror to Cloud Resync (SM-C Resync). La funzionalità semplifica la protezione dei dati durante la migrazione dei volumi negli ambienti NetApp. Questa versione aggiunge il supporto per SM-C Resync su ONTAP S3 e su altri provider compatibili con S3, come Wasabi e MinIO.



=== Porta il tuo bucket per StorageGRID

Quando si creano file di backup nell'archiviazione oggetti per un ambiente di lavoro, per impostazione predefinita, BlueXP Backup and Recovery crea il contenitore (bucket o account di archiviazione) per i file di backup nell'account di archiviazione oggetti configurato. In precedenza, era possibile ignorare questa impostazione e specificare un contenitore personalizzato per Amazon S3, Azure Blob Storage e Google Cloud Storage. Con questa versione, è ora possibile utilizzare il proprio contenitore di archiviazione oggetti StorageGRID.

Vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-protection-journey.html#do-you-want-to-create-your-own-object-storage-container["Crea il tuo contenitore di archiviazione di oggetti"].



== 13 maggio 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Risincronizzazione da SnapMirror al cloud per le migrazioni dei volumi

La funzionalità risincronizzazione da SnapMirror al cloud ottimizza la data Protection e la continuità durante le migrazioni dei volumi negli ambienti NetApp. Quando un volume viene migrato usando la replica logica SnapMirror (LRSE), da un'implementazione NetApp on-premise a un'altra o a una soluzione basata sul cloud come Cloud Volumes ONTAP o Cloud Volumes Service, SnapMirror to Cloud Resync garantisce che i backup cloud esistenti rimangano intatti e operativi.

Questa funzionalità elimina la necessità di un'operazione di re-baseline, che richiede molto tempo e risorse, consentendo alle operazioni di backup di continuare anche dopo la migrazione. Questa funzionalità è molto utile negli scenari di migrazione dei carichi di lavoro, a supporto di FlexVol e gruppi di lavoro, ed è disponibile a partire dalla versione 9.16.1 di ONTAP.

Mantenendo la continuità del backup in tutti gli ambienti, SnapMirror to Cloud Resync migliora l'efficienza delle operazioni e riduce la complessità della gestione dei dati nel cloud ibrido e multicloud.

Per informazioni dettagliate su come eseguire l'operazione di risincronizzazione, vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/task-migrate-volumes-snapmirror-cloud-resync.html["Migra i volumi usando SnapMirror per la risincronizzazione del cloud"].



=== Supporto per archivio oggetti MinIO di terze parti (anteprima)

Il backup e ripristino di BlueXP  ora estende il suo supporto ad archivi di oggetti di terze parti, con una particolare attenzione al MinIO. Questa nuova funzione di anteprima consente di sfruttare qualsiasi archivio di oggetti compatibile con S3 per le proprie esigenze di backup e recovery.

Con questa versione di anteprima, speriamo di garantire una solida integrazione con gli archivi di oggetti di terze parti prima che venga implementata la funzionalità completa. Siete incoraggiati ad esplorare questa nuova funzionalità e a fornire feedback per contribuire a migliorare il servizio.


IMPORTANT: Questa funzione non deve essere utilizzata in produzione.

*Limiti del modo Anteprima*

Mentre questa funzione è in anteprima, esistono alcune limitazioni:

* Il servizio Bring Your Own Bucket (BYOB) non è supportato.
* L'attivazione di DataLock nel criterio non è supportata.
* L'attivazione della modalità archiviazione nel criterio non è supportata.
* Sono supportati solo gli ambienti ONTAP on-premise.
* MetroCluster non è supportato.
* Le opzioni per abilitare la crittografia a livello di bucket non sono supportate.


*Guida introduttiva*

Per iniziare a utilizzare questa funzione di anteprima, è necessario attivare un contrassegno sul connettore BlueXP . È quindi possibile immettere i dettagli di connessione dell'archivio oggetti di terze parti MinIO nel flusso di lavoro di protezione scegliendo l'archivio oggetti compatibile con terze parti nella sezione di backup.

Per istruzioni su come attivare le funzioni di anteprima, vedere https://docs.netapp.com/us-en/bluexp-backup-recovery/task-preview-enable.html["Attivare le funzioni di anteprima nel backup e ripristino di BlueXP "].



== 16 aprile 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Miglioramenti dell'interfaccia utente

Questa versione migliora l'esperienza dell'utente semplificando l'interfaccia:

* La rimozione della colonna aggregate dalle tabelle Volumes, insieme alle colonne Snapshot Policy, Backup Policy e Replication Policy dalla tabella Volume nella dashboard V2, consente di ottimizzare il layout.
* L'esclusione degli ambienti di lavoro non attivati dall'elenco a discesa rende l'interfaccia meno ingombrante, la navigazione più efficiente e il caricamento più rapido.
* Mentre l'ordinamento nella colonna Tag è disattivato, è comunque possibile visualizzare i tag, garantendo che le informazioni importanti rimangano facilmente accessibili.
* La rimozione delle etichette sulle icone di protezione contribuisce a un aspetto più pulito e riduce i tempi di caricamento.
* Durante il processo di attivazione dell'ambiente di lavoro, una finestra di dialogo visualizza un'icona di caricamento per fornire un feedback fino al completamento del processo di rilevamento, migliorando la trasparenza e la sicurezza nelle operazioni del sistema.




=== Dashboard volume avanzato (anteprima)

La Volume Dashboard viene ora caricata in meno di 10 secondi, fornendo un'interfaccia molto più veloce ed efficiente. Questa versione in anteprima è disponibile per alcuni clienti, offrendo loro un'anteprima di questi miglioramenti.



=== Supporto per archivio oggetti Wasabi di terze parti (anteprima)

Il backup e recovery di BlueXP  ora estende il suo supporto ad archivi di oggetti di terze parti, con una particolare attenzione al tema di Wasabi. Questa nuova funzione di anteprima consente di sfruttare qualsiasi archivio di oggetti compatibile con S3 per le proprie esigenze di backup e recovery.



==== Per iniziare con Wasabi

Per iniziare a utilizzare lo storage di terze parti come archivio di oggetti, è necessario abilitare un flag all'interno di BlueXP  Connector. Quindi, puoi immettere i dettagli di connessione per l'archivio di oggetti di terze parti e integrarlo nei tuoi flussi di lavoro di backup e recovery.

.Fasi
. SSH nel connettore.
. Andare nel contenitore di server cbs di backup e ripristino BlueXP :
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Aprire il `default.json` file all'interno della `config` cartella tramite VIM o qualsiasi altro editor:
+
[listing]
----
vi default.json
----
. Modify `allow-s3-compatible`: false to : `allow-s3-compatible` true.
. Salvare le modifiche.
. Uscire dal contenitore.
. Riavviare il contenitore del server cbs di backup e ripristino BlueXP .


.Risultato
Una volta RIACCESO IL contenitore, aprire l'interfaccia utente di backup e ripristino di BlueXP . Quando avvii un backup o modifichi una strategia di backup, vengono visualizzati il nuovo provider "S3 compatibile" e gli altri provider di backup di AWS, Microsoft Azure, Google Cloud, StorageGRID e ONTAP S3.



==== Limitazioni della modalità di anteprima

Mentre questa funzione è in anteprima, considerare le seguenti limitazioni:

* Il servizio Bring Your Own Bucket (BYOB) non è supportato.
* L'attivazione di DataLock in un criterio non è supportata.
* L'attivazione della modalità archiviazione in un criterio non è supportata.
* Sono supportati solo gli ambienti ONTAP on-premise.
* MetroCluster non è supportato.
* Le opzioni per abilitare la crittografia a livello di bucket non sono supportate.


Durante questa anteprima, ti consigliamo di esplorare questa nuova funzionalità e di fornire un feedback sull'integrazione con gli archivi di oggetti di terze parti prima dell'implementazione della funzionalità completa.



== 17 marzo 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Esplorazione delle istantanee SMB

Questo aggiornamento di backup e ripristino di BlueXP  ha risolto un problema che ha impedito ai clienti di sfogliare gli snapshot locali in un ambiente SMB.



=== Update dell'ambiente AWS GovCloud

Questo aggiornamento di backup e ripristino di BlueXP  ha risolto un problema che impediva la connessione dell'interfaccia utente a un ambiente AWS GovCloud a causa di errori di certificato TLS. Il problema è stato risolto utilizzando il nome host del connettore BlueXP  anziché l'indirizzo IP.



=== Limiti di conservazione della politica di backup

In precedenza, l'interfaccia utente di backup e recovery di BlueXP  limitava i backup a 999 copie, mentre l'interfaccia a riga di comando consentiva di eseguire ulteriori operazioni. Ora, è possibile collegare fino a 4.000 volumi a una policy di backup e includere 1.018 volumi non collegati a una policy di backup. Questo aggiornamento include convalide aggiuntive che impediscono di superare questi limiti.



=== Risincronizzazione del cloud SnapMirror

Questo aggiornamento garantisce che la risincronizzazione del cloud SnapMirror non possa essere avviata dal backup e ripristino di BlueXP  per le versioni ONTAP non supportate dopo l'eliminazione di una relazione SnapMirror.



== 21 febbraio 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Indicizzazione ad alte prestazioni

Il backup e ripristino di BlueXP  introduce una funzionalità di indicizzazione aggiornata che rende più efficiente l'indicizzazione dei dati nell'ambiente di lavoro di origine. La nuova funzione di indicizzazione include aggiornamenti all'interfaccia utente, prestazioni migliorate del metodo di ricerca e ripristino per il ripristino dei dati, aggiornamenti alle funzionalità di ricerca globale e una migliore scalabilità.

Ecco una descrizione dei miglioramenti:

* *Consolidamento cartelle*: La versione aggiornata raggruppa le cartelle utilizzando nomi che includono identificatori specifici, rendendo più agevole il processo di indicizzazione.
* *Compattazione dei file in parquet*: La versione aggiornata riduce il numero di file utilizzati per l'indicizzazione di ciascun volume, semplificando il processo e eliminando la necessità di un database aggiuntivo.
* *Scale-out con più sessioni*: La nuova versione aggiunge più sessioni per gestire le attività di indicizzazione, velocizzando il processo.
* *Supporto per più contenitori indice*: La nuova versione utilizza più contenitori per gestire e distribuire meglio le attività di indicizzazione.
* *Split index workflow*: La nuova versione divide il processo di indicizzazione in due parti, migliorando l'efficienza.
* *Concorrenza migliorata*: La nuova versione consente di eliminare o spostare le directory contemporaneamente, velocizzando il processo di indicizzazione.


.Chi trae vantaggio da questa funzione?
La nuova funzione di indicizzazione è disponibile per tutti i nuovi clienti.

.Come si attiva l'indicizzazione?
Prima di poter utilizzare il metodo Search & Restore per il ripristino dei dati, è necessario attivare l'indicizzazione in ogni ambiente di lavoro di origine da cui si prevede di ripristinare volumi o file. Ciò consente al Catalogo indicizzato di tenere traccia di ogni volume e di ogni file di backup, rendendo le ricerche veloci ed efficienti.

Attivare l'indicizzazione nell'ambiente di lavoro di origine selezionando l'opzione "Abilita indicizzazione" quando si esegue una ricerca e ripristino.

Per ulteriori informazioni, consultare la documentazione https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-search-restore["Come ripristinare i dati ONTAP utilizzando Cerca  Ripristina"].

.Scala supportata
La nuova funzione di indicizzazione supporta quanto segue:

* Efficienza della ricerca globale in meno di 3 minuti
* Fino a 5 miliardi di file
* Fino a 5000 volumi per cluster
* Fino a 100K snapshot per volume
* Il tempo massimo per l'indicizzazione della linea di base è inferiore a 7 giorni. Il tempo effettivo varia a seconda dell'ambiente.




=== Miglioramenti alle performance della ricerca globale

Questa versione include anche miglioramenti alle prestazioni della ricerca globale. Verranno ora visualizzati indicatori di avanzamento e risultati di ricerca più dettagliati, inclusi il conteggio dei file e il tempo richiesto per la ricerca. I contenitori dedicati per la ricerca e l'indicizzazione garantiscono che le ricerche globali vengano completate in meno di cinque minuti.

Tenere presente queste considerazioni relative alla ricerca globale:

* Il nuovo indice non viene eseguito sulle istantanee etichettate come ogni ora.
* La nuova funzione di indicizzazione funziona solo sugli snapshot su FlexVol e non sugli snapshot su FlexGroup.




== 13 febbraio 2025

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Versione di anteprima BlueXP backup and recovery

Questa versione di anteprima del BlueXP backup and recovery fornisce un'interfaccia utente aggiornata che consente di gestire i carichi di lavoro di Microsoft SQL Server utilizzando una strategia di protezione 3-2-1, nota nel servizio BlueXP backup and recovery . Con questa nuova versione, è possibile eseguire il backup di questi carichi di lavoro sullo storage primario, replicarli sullo storage secondario ed eseguirne il backup sullo storage di oggetti cloud.


NOTE: QUESTA DOCUMENTAZIONE VIENE FORNITA COME ANTEPRIMA TECNOLOGICA. Con questa offerta di anteprima, NetApp si riserva il diritto di modificare i dettagli dell'offerta, i contenuti e la tempistica prima della disponibilità generale.

Questa versione di BlueXP backup and recovery Preview 2025 include i seguenti aggiornamenti.

* Un'interfaccia utente riprogettata che offre un'esperienza più intuitiva per la gestione delle attività di backup e ripristino.
* La versione di anteprima consente di eseguire il backup e il ripristino dei database Microsoft SQL Server. (Il supporto per altri carichi di lavoro verrà aggiunto nelle versioni future.)
* Questa versione integra le funzionalità SnapCenter , consentendo di gestire e proteggere le risorse SnapCenter con una strategia di protezione dei dati 3-2-1 dall'interfaccia utente BlueXP backup and recovery .
* Questa versione consente di importare carichi di lavoro SnapCenter nel BlueXP backup and recovery.




== 22 novembre 2024

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Modalità di protezione SnapLock Compliance e SnapLock Enterprise

Il backup e recovery di BlueXP  ora può eseguire il backup dei volumi on-premise FlexVol e FlexGroup configurati con le modalità di protezione SnapLock Compliance o SnapLock Enterprise. Per supportare questo tipo di supporto, i cluster devono eseguire ONTAP 9,14 o versione successiva. Il backup dei volumi FlexVol utilizzando la modalità SnapLock Enterprise è supportato a partire dalla versione ONTAP 9.11.1. Le release precedenti di ONTAP non supportano il backup di volumi di protezione SnapLock.

Consultare l'elenco completo dei volumi supportati nella https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Informazioni su backup e ripristino BlueXP"] .



=== Indicizzazione per il processo di ricerca e ripristino nella pagina dei volumi

Prima di utilizzare Search & Restore, è necessario attivare l'indicizzazione su ogni ambiente di lavoro di origine da cui si desidera ripristinare i dati dei volumi. In questo modo, il catalogo indicizzato può tenere traccia dei file di backup per ogni volume. La pagina volumi ora mostra lo stato di indicizzazione:

* Indicizzato: I volumi sono stati indicizzati.
* In corso
* Non indicizzato
* Indicizzazione in pausa
* Errore
* Non attivato




== 27 settembre 2024

Questa versione di backup e ripristino di BlueXP  include i seguenti aggiornamenti.



=== Supporto Podman su RHEL 8 o 9 con Browse and Restore

Il backup e il ripristino di BlueXP  ora supporta il ripristino di file e cartelle su Red Hat Enterprise Linux (RHEL) versioni 8 e 9 utilizzando il motore Podman. Ciò si applica al metodo di ricerca e ripristino del backup e ripristino di BlueXP .

BlueXP  Connector versione 3.9.40 supporta alcune versioni di Red Hat Enterprise Linux versione 8 e 9 per qualsiasi installazione manuale del software del connettore su un host RHEL 8 o 9, indipendentemente dalla posizione in cui si trovano oltre ai sistemi operativi menzionati nella https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["requisiti dell'host"^] . Queste nuove versioni RHEL richiedono il motore Podman anziché Docker. In precedenza, il backup e il ripristino di BlueXP  avevano due limitazioni quando si utilizzava il motore Podman. Queste limitazioni sono state rimosse.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Ulteriori informazioni sul ripristino dei dati ONTAP dai file di backup"].



=== L'indicizzazione più rapida dei cataloghi migliora la ricerca e il ripristino

Questa versione include un indice di catalogo migliorato che completa l'indicizzazione della linea di base molto più velocemente. L'indicizzazione più rapida consente di utilizzare più rapidamente la funzione Cerca e ripristina.

https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html["Ulteriori informazioni sul ripristino dei dati ONTAP dai file di backup"].
