= Miglioramenti dell'interfaccia utente
:allow-uri-read: 




=== Miglioramenti dell'interfaccia utente

Questa versione migliora l'esperienza dell'utente semplificando l'interfaccia:

* La rimozione della colonna aggregate dalle tabelle Volumes, insieme alle colonne Snapshot Policy, Backup Policy e Replication Policy dalla tabella Volume nella dashboard V2, consente di ottimizzare il layout.
* L'esclusione degli ambienti di lavoro non attivati dall'elenco a discesa rende l'interfaccia meno ingombrante, la navigazione più efficiente e il caricamento più rapido.
* Mentre l'ordinamento nella colonna Tag è disattivato, è comunque possibile visualizzare i tag, garantendo che le informazioni importanti rimangano facilmente accessibili.
* La rimozione delle etichette sulle icone di protezione contribuisce a un aspetto più pulito e riduce i tempi di caricamento.
* Durante il processo di attivazione dell'ambiente di lavoro, una finestra di dialogo visualizza un'icona di caricamento per fornire un feedback fino al completamento del processo di rilevamento, migliorando la trasparenza e la sicurezza nelle operazioni del sistema.




=== Dashboard volume avanzato (anteprima)

La Volume Dashboard viene ora caricata in meno di 10 secondi, fornendo un'interfaccia molto più veloce ed efficiente. Questa versione in anteprima è disponibile per alcuni clienti, offrendo loro un'anteprima di questi miglioramenti.



=== Supporto per archivio oggetti Wasabi di terze parti (anteprima)

Il backup e recovery di BlueXP  ora estende il suo supporto ad archivi di oggetti di terze parti, con una particolare attenzione al tema di Wasabi. Questa nuova funzione di anteprima consente di sfruttare qualsiasi archivio di oggetti compatibile con S3 per le proprie esigenze di backup e recovery.



==== Per iniziare con Wasabi

Per iniziare a utilizzare lo storage di terze parti come archivio di oggetti, è necessario abilitare un flag all'interno di BlueXP  Connector. Quindi, puoi immettere i dettagli di connessione per l'archivio di oggetti di terze parti e integrarlo nei tuoi flussi di lavoro di backup e recovery.

.Fasi
. SSH nel connettore.
. Andare nel contenitore di server cbs di backup e ripristino BlueXP :
+
[listing]
----
docker exec -it cloudmanager_cbs sh
----
. Aprire il `default.json` file all'interno della `config` cartella tramite VIM o qualsiasi altro editor:
+
[listing]
----
vi default.json
----
. Modify `allow-s3-compatible`: false to : `allow-s3-compatible` true.
. Salvare le modifiche.
. Uscire dal contenitore.
. Riavviare il contenitore del server cbs di backup e ripristino BlueXP .


.Risultato
Una volta RIACCESO IL contenitore, aprire l'interfaccia utente di backup e ripristino di BlueXP . Quando avvii un backup o modifichi una strategia di backup, vengono visualizzati il nuovo provider "S3 compatibile" e gli altri provider di backup di AWS, Microsoft Azure, Google Cloud, StorageGRID e ONTAP S3.



==== Limitazioni della modalità di anteprima

Mentre questa funzione è in anteprima, considerare le seguenti limitazioni:

* Il servizio Bring Your Own Bucket (BYOB) non è supportato.
* L'attivazione di DataLock in un criterio non è supportata.
* L'attivazione della modalità archiviazione in un criterio non è supportata.
* Sono supportati solo gli ambienti ONTAP on-premise.
* MetroCluster non è supportato.
* Le opzioni per abilitare la crittografia a livello di bucket non sono supportate.


Durante questa anteprima, ti consigliamo di esplorare questa nuova funzionalità e di fornire un feedback sull'integrazione con gli archivi di oggetti di terze parti prima dell'implementazione della funzionalità completa.
