= Supporto del carico di lavoro Kubernetes come anteprima tecnologica pubblica
:allow-uri-read: 




=== Supporto del carico di lavoro Kubernetes come anteprima tecnologica pubblica

Questa versione di BlueXP backup and recovery introduce il supporto per l'individuazione e la gestione dei carichi di lavoro Kubernetes:

* Scopri i cluster Red Hat OpenShift e Kubernetes open source, supportati da NetApp ONTAP, senza condividere i file kubeconfig.
* Scopri, gestisci e proteggi le applicazioni su più cluster Kubernetes utilizzando un piano di controllo unificato.
* Trasferisci le operazioni di spostamento dei dati per il backup e il ripristino delle applicazioni Kubernetes a NetApp ONTAP.
* Orchestrare i backup delle applicazioni locali e basati su storage di oggetti.
* Esegui il backup e il ripristino di intere applicazioni e singole risorse su qualsiasi cluster Kubernetes.
* Lavora con container e macchine virtuali in esecuzione su Kubernetes.
* Crea backup coerenti con l'applicazione utilizzando modelli e hook di esecuzione.

